### ISSUE TITLE
How to update the tools? (ie. civix)

### ISSUE THREAD

**Issue by tttp** [civicrm/civicrm-buildkit#113]
on your doc: "New versions of buildkit are likely to include new versions of tools. The new tools will download automatically when you first run "civibuild". If you prefer to download explicitly, then re-run "civi-download-tools"."

but when I run civi-download-tools:

[Composer binary (/usr/src/civicrm-buildkit/bin/composer) already exists. Skipping.]]
[[composer dependencies already installed. Skipping.]]
[[civix binary (/usr/src/civicrm-buildkit/bin/civix) already exists. Skipping.]]
...

Is there a way to force?
ideally, some tools (eg civix are installed using git clone --depth=1) so I can cd extern/civix and git pull

**Comment by totten** [comment]
I think this discussion may have gotten a bit side-tracked -- the original question was, "Is there a way to force download of foo?" to which the answer is "Yes. Delete foo and rerun."
