### ISSUE TITLE
is there a way to control the database name(s)

### ISSUE THREAD

**Issue by tttp** [civicrm/civicrm-buildkit#114]
Hi,

 with various tests and crash during the install, I end up with loads of databases that have the same pattern drupaldemo_{random}. is there a way to
1) have a single database for each site instead of two?
2) control or skip the {random} at the end (rationale: if I have several databases with the same site name, I got something wrong I'd investigate beside of piling stalled databases.

right now, drush civicrm-sql-cli connects to the drupal db, that makes it even more annoying not to be able to see which database is the right one by its name ;)

**Comment by totten** [comment]
This duplicates https://github.com/totten/amp/issues/34
