### ISSUE TITLE
Not very views-friendly

### ISSUE THREAD

**Issue by colemanw** [civicrm/civicrm-buildkit#117]
When spinning up a new drupal install, buildkit creates separate databases with different sql users.
To get views working one must manually copy-paste the db code to settings.php and also grant select permissions to the sql user of one db to the other.

**Comment by MikeyMJCO** [comment]
Is this issue still relevant?

**Comment by eileenmcnaughton** [comment]
This is a test to see if the stale issue message will be REMOVED again if a comment is made

**Comment by MikeyMJCO** [comment]
Survey says - no :-p

**Comment by eileenmcnaughton** [comment]
:-)
