### ISSUE TITLE
error with setfacl

### ISSUE THREAD

**Issue by jmcclelland** [civicrm/civicrm-buildkit#121]
I'm running debian wheezy.

When I ran the command:

./amp config

I chose the linuxACL option and www-data as the web user. No errors.

Then, when I ran:

./amp test I got:

civicrm@piglet:/var/www/test/civicrm-buildkit/bin$ ./amp test
Create test application
Create data directory: /home/civicrm/.amp/canary/data/4cJePYaQav6IYhZLF1MJkVvp2Iq1T38N
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'setfacl: /home/civicrm/.amp/canary/data/4cJePYaQav6IYhZLF1MJkVvp2Iq1T38N: Operation not supported
' in /var/www/test/civicrm-buildkit/vendor/totten/amp/src/Amp/Permission/External.php:43
Stack trace:
#0 /var/www/test/civicrm-buildkit/vendor/totten/amp/src/Amp/Command/DatadirCommand.php(43): Amp\Permission\External->applyDirPermission('write', '/home/civicrm/....')
#1 /var/www/test/civicrm-buildkit/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(241): Amp\Command\DatadirCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/test/civicrm-buildkit/vendor/totten/amp/src/Amp/Command/ContainerAwareCommand.php(26): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/test/civicrm-buildkit/vendor/totten/amp/src/Amp/Command/TestCommand.php(117): Amp\Comm in /var/www/test/civicrm-buildkit/vendor/totten/amp/src/Amp/Permission/External.php on line 43

Fatal error: Uncaught exception 'RuntimeException' with message 'setfacl: /home/civicrm/.amp/canary/data/4cJePYaQav6IYhZLF1MJkVvp2Iq1T38N: Operation not supported
' in /var/www/test/civicrm-buildkit/vendor/totten/amp/src/Amp/Permission/External.php:43
Stack trace:
#0 /var/www/test/civicrm-buildkit/vendor/totten/amp/src/Amp/Command/DatadirCommand.php(43): Amp\Permission\External->applyDirPermission('write', '/home/civicrm/....')
#1 /var/www/test/civicrm-buildkit/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(241): Amp\Command\DatadirCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/test/civicrm-buildkit/vendor/totten/amp/src/Amp/Command/ContainerAwareCommand.php(26): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/test/civicrm-buildkit/vendor/totten/amp/src/Amp/Command/TestCommand.php(117): Amp\Comm in /var/www/test/civicrm-buildkit/vendor/totten/amp/src/Amp/Permission/External.php on line 43
civicrm@piglet:/var/www/test/civicrm-buildkit/bin$

My user is in the www-group already. Does this need to be run as root?

**Comment by totten** [comment]
It shouldn't be necessary to run amp or setfacl as root. (That's the neat thing about setfacl.) But -- depending on the distro+filesystem -- it may be necessary to enable ACLs in fstab.
 * https://help.ubuntu.com/community/FilePermissionsACLs#Enabling_ACLs_in_the_Filesystem (The instructions should be the same for most Debian-based distros.)
 * https://github.com/totten/amp/blob/master/doc/perm.md

**Comment by jmcclelland** [comment]
Ug. And again user error. Apologies! The filesystem was not, in fact, mounted with ACLs enabled.
