### ISSUE TITLE
"failed to open stream" when running ./amp test

### ISSUE THREAD

**Issue by jmcclelland** [civicrm/civicrm-buildkit#122]
To get through my earlier error (#121), I re-configured permission to "Loose".

Then, when I ran ./amp test I got:

		civicrm@piglet:/var/www/test/civicrm-buildkit/bin$ ./amp test
		Create test application
		Create data directory: /home/civicrm/.amp/canary/data/xxxxxxxxxxxxxxxxxxxxx
		AMP_URL='http://localhost:7979'
		AMP_ROOT='/home/civicrm/.amp/canary'
		AMP_DB_DSN='mysql://canary_dnil7:xxxxxxxxxxxxxxx@127.0.0.1:3306/canary_dnil7?new_link=true'
		AMP_DB_USER='canary_dnil7'
		AMP_DB_PASS='xxxxxxxxxxxxxxxx'
		AMP_DB_HOST='127.0.0.1'
		AMP_DB_PORT='3306'
		AMP_DB_NAME='canary_dnil7'
		AMP_DB_ARGS='-h 127.0.0.1 -u canary_dnil7 -pxxxxxxxxxxxxxxxx -P 3306 canary_dnil7'

		Connect to test application
		Expect response: "response-code-0scdfw0yPk"
		PHP Warning:  file_get_contents(http://localhost:7979/index.php): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error
		 in /var/www/test/civicrm-buildkit/vendor/totten/amp/src/Amp/Command/TestCommand.php on line 153

		Warning: file_get_contents(http://localhost:7979/index.php): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error
		 in /var/www/test/civicrm-buildkit/vendor/totten/amp/src/Amp/Command/TestCommand.php on line 153
		Received incorrect response: ""
		Tip: Try running "amp config" and/or restarting the webserver.
		civicrm@piglet:/var/www/test/civicrm-buildkit/bin$

And the log file reports:

		[Mon Jan 05 10:03:47 2015] [crit] [client 127.0.0.1] configuration error:  couldn't perform authentication. AuthType not set!: /index.php

**Comment by totten** [comment]
FWIW: http://stackoverflow.com/questions/21265191/apache-authtype-not-set-500-error

This page suggests that the error arises on Apache 2.4 when the directive "Require all granted" is missing. (Unfortunately, the directive is invalid on Apache <2.4.) When running "amp config", one can set "httpd_type" to "apache" or "apache24". The difference is that "apache24" includes the directive "Require all granted".

 * https://github.com/totten/amp/blob/master/src/Amp/views/apache-vhost.php
 * https://github.com/totten/amp/blob/master/src/Amp/views/apache24-vhost.php

Some suggestions:

 * Check the "httpd_type" setting 
 * Check the actual version of Apache
 * Run "./amp test ; sudo apache2ctl restart; ./amp test"
 * If problems persist, edit the template (vendor/totten/amp/src/Amp/views/apache*vhost.php) and retest (as above).

**Comment by totten** [comment]
Alternatively, you could do "amp config:set --httpd_type=none" and then manually configure the vhost yourself.

**Comment by jmcclelland** [comment]
I'm so embarrassed! user error - I had the version of apache wrong. Sorry to waste your time.
