### ISSUE TITLE
vagrant install fails on npm install karma

### ISSUE THREAD

**Issue by kcristiano** [civicrm/civicrm-buildkit#141]
I am attempting to set up buildkit with vagrant.  

Initial run fails as nodejs and npm are missing. After adding the packages to bootstrap.sh, node and npm install fine, but then I get this error:

-----------

default: npm http GET https://registry.npmjs.org/bower
default: npm http GET https://registry.npmjs.org/jasmine-core
default: npm http GET https://registry.npmjs.org/jshint
default: npm http GET https://registry.npmjs.org/karma
default: npm http GET https://registry.npmjs.org/karma-chrome-launcher
default: npm http GET https://registry.npmjs.org/karma-jasmine
default: npm http GET https://registry.npmjs.org/karma-junit-reporter
default: npm http GET https://registry.npmjs.org/karma-ng-html2js-preprocessor
default: npm http GET https://registry.npmjs.org/karma-phantomjs-launcher
default: npm ERR! Error: failed to fetch from registry: karma
default: npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
default: npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
default: npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
default: npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
default: npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
default: npm ERR!     at Request.emit (events.js:88:20)
default: npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
default: npm ERR!     at ClientRequest.emit (events.js:67:17)
default: npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
default: npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
default: npm ERR! You may report this log at:
default: npm ERR!     <http://bugs.debian.org/npm>
default: npm ERR! or use
default: npm ERR!     reportbug --attach /home/vagrant/buildkit/npm-debug.log npm
default: npm ERR!
default: npm ERR! System Linux 3.2.0-23-generic-pae
default: npm ERR! command "node" "/usr/bin/npm" "install"
default: npm ERR! cwd /home/vagrant/buildkit
default: npm ERR! node -v v0.6.12
default: npm ERR! npm -v 1.1.4
default: npm ERR! message failed to fetch from registry: karma
default: npm ERR!
default: npm ERR! Additional logging details can be found in:
default: npm ERR!     /home/vagrant/buildkit/npm-debug.log
default: npm not ok 

-----------
looks like it is failing on 'karma'.  On another attempt, it failed on js hint.

Any suggestions on getting this running?  My goal was to have my enire team use civibuild, but we are not all on the same platform and a vagrant install would be great.  Not to mention, this was the best way to deal with working with devs that use windows machines.

**Comment by totten** [comment]
Vagrant support moving to https://github.com/civicrm/civicrm-buildkit-vagrant . That box does not currently have this failure.
