### ISSUE TITLE
setup.sh has 'set -x'

### ISSUE THREAD

**Issue by ferriswheel** [civicrm/civicrm-buildkit#144]
see here  in bin/setup.sh

<pre>
137 ###############################################################################
138 ## Execute tasks
139 set -x
140 
141 if [ -n "$DO_DOWNLOAD" ]; then
</pre>

**Comment by totten** [comment]
I suppose that makes it a little noisy... is that a problem? It's really handy when something fails (eg when automatically testing PRs, we do a fresh build, and it's easier to diagnose the failures if the build log has a lot of detail).
