### ISSUE TITLE
buildkit install failing on phantomjs install

### ISSUE THREAD

**Issue by joemcl** [civicrm/civicrm-buildkit#145]
I keep getting this failure message, below, when running civi-download-tools. I installed phantomjs from source last night but it's not recognized as already installed. I think the issue is that the install script needs to contain nodejs install.js as well as/instead of node install.js . 

Also, my installed directory is 
~/buildkit/node_modules/karma-chrome-launcher/node_modules/ 
not 
~buildkit/node_modules/karma-phantomjs-launcher/node_modules/phantomjs

so I'll figure out where phantomjs is actually installed. 

>  phantomjs@1.9.16 install /home/owner/buildkit/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
> node install.js

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.16 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-34-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/owner/buildkit
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/owner/buildkit/npm-debug.log
npm ERR! not ok code 0

**Comment by joemcl** [comment]
I'm thinking I just have to add phantomjs to PATH correctly so the script recognizes it as installed from source already. Checking that out.

**Comment by GinkgoFJG** [comment]
@joemcl: Sounds like you're missing the nodejs-legacy package, which basically aliases nodejs to node. If you're on a Debian-based system like Ubuntu, you can do:
`sudo apt-get install nodejs-legacy`

**Comment by joemcl** [comment]
yup @GinkgoFJG that was the problem. Buildkit install finished. Thanks so much.
