### ISSUE TITLE
Update to support current version of nodejs

### ISSUE THREAD

**Issue by JoeMurray** [civicrm/civicrm-buildkit#150]
FYI, re-running install I see buildkit is expecting an old version of nodejs. Might be nice to support current:

Joes-MacBook-Pro:buildkit josephmurray$ ./bin/civi-download-tools 
[[Composer binary (/Users/josephmurray/Sites/civicrm/buildkit/bin/composer) already exists. Skipping.]]
[[composer dependencies already installed. Skipping.]]
npm WARN engine karma@0.12.32: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"0.12.3","npm":"2.9.1"})

**Comment by totten** [comment]
This seems to be a non-critical warning. I recently installed on a new Ubuntu build with NodeJS v0.12 (from the nodesource repo): the warning appeared, and it seemed slow, but it did install, and it seems to run. The [documentation](http://karma-runner.github.io/0.12/intro/installation.html) says that node@0.12 is supported.

This seems to be a known issue upstream which they're working on (eg https://github.com/karma-runner/karma/issues/1378 and https://github.com/karma-runner/karma/issues/1415).
