### ISSUE TITLE
How to fetch CiViCRM events externally [ Drupal 7]

### ISSUE THREAD

**Issue by Parthvora** [civicrm/civicrm-buildkit#162]
I'm new to CiViCRM. I want to fetch events which are created in CiViCRM which is hosted on another server. So basically I want to fetch CiViCRM data from one individual site to my site. I don't know that which are the ways to do it and which is the best one. But I think Rest option would be good if I'm not wrong. I'm not able to find any similar example which is near to my task. All I don't understand that how should I use my rest url with code:

1) Option 1: 

 $api = new civicrm_api3(array ('server' => 'http://localhost/abc',

  'api_key'=>'123456789',
  'key'=>'123xyzABC'));

2) Option 2:

     $contactxml =       simplexml_load_file("http://localhost/abc/sites/all/modules/civicrm/extern /rest.php?entity=contact&action=get&key=<site    key>&api_key=$apikey&last_name=Koot");
      foreach ($contactxml->children() as $contact) {
        $display = $contact->display_name;
      }

Is there any other options. I want to go for option 1 if that is possible. And I want response in JSON if possible. 

Any help wound be appreciated.   

Thanks

**Comment by totten** [comment]
This repository is for tracking buildkit, which is a collection of third-party utilities and build scripts that help with Civi development. For posting questions about Civi's API, I'd suggest http://civicrm.stackexchange.com/

Aside: For something akin to 1, you might look at https://github.com/civicrm/civicrm-core/blob/master/api/class.api.php . But again, it's better to ask that kind of question at StackExchange.
