### ISSUE TITLE
Ubuntu 14.10  install/buildkit

### ISSUE THREAD

**Issue by zorgalina** [civicrm/civicrm-buildkit#164]
On Ubuntu 14.10 (on VirtualBox) buildkit - got "WARNING: Failed to locate command "node". NodeJS (http://nodejs.org/) is required for development of CiviCRM v4.6+." and "WARNING: Failed to locate command "node". NodeJS (http://nodejs.org/) is required for development of CiviCRM v4.6+."  - I installed separately following instructions here: https://github.com/joyent/node/wiki/installing-node.js-via-package-manager

**Comment by totten** [comment]
So as background... in the past, there's been a discrepancy in the past between different NodeJS packages:

  * NodeSource packages installed `/usr/bin/node` -- which matches the official binaries and most documentation. (I've observed this in Ubuntu 12.04 and 14.04.)
  * Debian.org/Ubuntu.com packages renamed the command to `/usr/bin/nodejs` (which avoids a conflict with another Debian package). However, for compatibility, one can install an additional package (`nodejs-legacy`).

Some speculation: maybe NodeSource is experimenting with aligning the packages better in 14.10? Or maybe /etc/alternatives for node got messed up somehow? Or somehow you wound up with the Ubuntu.com package instead?

Regardless, if you can find the "node" or "nodejs" command, you can fix it by ensuring it shows up in the path, e.g.

```
$ dpkg -L nodejs | grep /usr/bin
/usr/bin
/usr/bin/nodejs
/usr/bin/npm
$ ln -s /usr/bin/nodejs /usr/local/bin/node
```

If the clusterf* of nodejs names is actually getting worse, then I suppose we'll have to do something a bit more heavy-handed to autodetect/wrap/adapt to whatever name is used locally.

**Comment by zorgalina** [comment]
Hello Tim, thanks for your reply - I may go back to deinstalling Civicrm
4.6, and buildkit, and trying again.   :(   I got the Ubuntu image named
ubuntu-14.10-desktop-amd64.vdi (I wanted a desktop not just a server).  I
found that indeed /usr/bin/nodejs is there and the command nodejs is
recognized. When I ran the commands I did a week or so ago (sudo apt-get
update, sudo apt-get install nodejs, sudo apt-get install npm) I ended up
with 1.)  a symlink for  /usr/bin/node  to  /etc/alternatives/node, and a
symlink at /etc/alternatives/node  back to /usr/bin/nodejs.  Sorry for any
confusion. Sorry for my own confusion.





On Mon, Jul 27, 2015 at 9:44 PM, Tim Otten <notifications@github.com> wrote:

> So as background... in the past, there's been a discrepancy in the past
> between different NodeJS packages:
>
>    - NodeSource packages installed /usr/bin/node -- which matches the
>    official binaries and most documentation. (I've observed this in Ubuntu
>    12.04 and 14.04.)
>    - Debian.org/Ubuntu.com packages renamed the command to /usr/bin/nodejs
>    (which avoids a conflict with another Debian package). However, for
>    compatibility, one can install an additional package (nodejs-legacy).
>
> Some speculation: maybe NodeSource is experimenting with aligning the
> packages better in 14.10? Or maybe /etc/alternatives for node got messed up
> somehow? Or somehow you wound up with the Ubuntu.com package instead?
>
> Regardless, if you can find the "node" or "nodejs" command, you can fix it
> by ensuring it shows up in the path, e.g.
>
> $ dpkg -L nodejs | grep /usr/bin
> /usr/bin
> /usr/bin/nodejs
> /usr/bin/npm
> $ ln -s /usr/bin/nodejs /usr/local/bin/node
>
> If the clusterf* of nodejs names is actually getting worse, then I suppose
> we'll have to do something a bit more heavy-handed to autodetect/wrap/adapt
> to whatever name is used locally.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-buildkit/issues/164#issuecomment-125443840>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by totten** [comment]
I hope it eventually worked out. FWIW, I've patched `civi-download-tools` to check for Debian's `nodejs` binary and attempt to workaround. https://github.com/civicrm/civicrm-buildkit/pull/173

**Comment by zorgalina** [comment]
Thanks Tim - I started over w/a new copy of buildkit and it did seem to
work out (but not sure why!)

On Mon, Aug 24, 2015 at 9:40 AM, Tim Otten <notifications@github.com> wrote:

> I hope it eventually worked out. FWIW, I've patched civi-download-tools
> to check for Debian's nodejs binary and attempt to workaround. #173
> <https://github.com/civicrm/civicrm-buildkit/pull/173>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/civicrm/civicrm-buildkit/issues/164#issuecomment-134294103>
> .
>



-- 
زورگلنه ءء لسلی
