### ISSUE TITLE
civibuild restore fails with mysql 5.6 / Ubuntu 15.04

### ISSUE THREAD

**Issue by aydun** [civicrm/civicrm-buildkit#167]
Just upgraded to Ubuntu 15.04 (from 14.10) which includes mysql 5.6

civibuild restore-all fails with:
```
2015-08-03 23:29:48 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2015-08-03 23:29:48 0 [Note] mysqld (mysqld 5.6.25-0ubuntu0.15.04.1) starting as process 12081 ...
2015-08-03 23:29:48 12081 [Warning] The option innodb (skip-innodb) is deprecated and will be removed in a future release
2015-08-03 23:29:48 12081 [ERROR] Unknown/unsupported storage engine: InnoDB
2015-08-03 23:29:48 12081 [ERROR] Aborting
```

**Comment by totten** [comment]
Hmm, "civibuild restore" is basically just `gunzip /path/to/snapshot.gz | mysql -u siteuser -psiteass -h hostname sitedb` , and I can't find anywhere that it would enable the option `skip-innodb`.

It looks like the `skip-innodb` option disables InnoDB, and most commenters on the Internet seem to regard it as a `my.cnf` or `mysqld` option. Unfortunately, I think an error here is the right behavior -- Civi relies on several features of InnoDB (eg foreign-keys, transactions, triggers) which aren't available in other storage engines.

Moreover, the MySQL docs highly recommend InnoDB and say that [`skip-innodb` is deprecated](https://dev.mysql.com/doc/refman/5.6/en/innodb-turning-off.html). It'd be really surprising (and problematic) if new installations of Ubuntu came with `skip-innodb` by default.

Any chance this is cruft/left-overs from working with some other app?

**Comment by aydun** [comment]
Digging a bit more, I'm using the ram_disk option and amp has:
```
vendor/totten/amp/src/Amp/Database/MySQLRAMServer.php:58:      $this->runCommand("{$this->mysqld_base_command} --log-warnings=0 --bootstrap --loose-skip-innodb --max_allowed_packet=8M --default-storage-engine=myisam --net_buffer_length=16K < {$this->tmp_path}/install_mysql.sql");
```
Removing ```--loose-skip-innodb``` lets it run, although I'm not sure why it is there.

**Comment by totten** [comment]
Thanks, good catch. I agree that's weird. Will need to investigate.

**Comment by totten** [comment]
I'm not sure if it works in Ubuntu 15.04, but I updated `amp` a while ago to support mysqld 5.7 on ramdisk with Ubuntu 16.04 -- https://github.com/amp-cli/amp/pull/42
