### ISSUE TITLE
civibuild download "$BLDNAME"... fails with permission denied

### ISSUE THREAD

**Issue by openbrian** [civicrm/civicrm-buildkit#172]
I'm following instructions here https://buildkit.civicrm.org/#/tutorials and my first build fails with this error message below.  Did i miss a step to grant www-data this permission?

Started by user brian
Building in workspace /var/lib/jenkins/jobs/ScheduledTest-drupal-clean/workspace
[workspace] $ /bin/bash /tmp/hudson5034185699702965011.sh
+ export PATH=/opt/buildkit/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
+ PATH=/opt/buildkit/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
+ BLDNAME=jenkins-1
+ BLDURL=http://localhost:8101
+ EXITCODE=0
+ '[' -d /var/lib/jenkins/jobs/ScheduledTest-drupal-clean/workspace/junit ']'
+ '[' -d /var/lib/jenkins/jobs/ScheduledTest-drupal-clean/workspace/civibuild-html ']'
+ '[' -d /opt/buildkit/build/jenkins-1 ']'
+ mkdir /var/lib/jenkins/jobs/ScheduledTest-drupal-clean/workspace/junit
+ mkdir /var/lib/jenkins/jobs/ScheduledTest-drupal-clean/workspace/civibuild-html
+ civibuild download jenkins-1 --civi-ver master --type drupal-clean
PHP Warning:  file_put_contents(/opt/buildkit/app/tmp/civi-download-tools.lock): failed to open stream: Permission denied in /opt/buildkit/bin/pidlockfile.php on line 91

Warning: file_put_contents(/opt/buildkit/app/tmp/civi-download-tools.lock): failed to open stream: Permission denied in /opt/buildkit/bin/pidlockfile.php on line 91
touch: cannot touch ‘/opt/buildkit/app/tmp/composer-data.md5’: Permission denied
Build step 'Execute shell' marked build as failure
[htmlpublisher] Archiving HTML reports...

**Comment by totten** [comment]
The user `www-data` shouldn't need any more permissions, but the SSH/Jenkins user does need write permission to `/opt/buildkit/app/tmp` and `/opt/buildkit/build`.

**Comment by openbrian** [comment]
I created buildkit on my system as "brian".  It will probably run much better, following your advice, to create this as "jenkins" by using 'sudo -u "jenkins" -H bash'.

**Comment by openbrian** [comment]
Hello!

 

New message, please read <http://vippzara.com/those.php?q>

 

brian@derocher.org

**Comment by openbrian** [comment]
Hello!

 

New message, please read <http://securetravelinternational.com/places.php?8ppp2>

 

brian@derocher.org
