### ISSUE TITLE
Running setup.sh with a argument fails for drupal 8

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/civicrm-buildkit#174]
Drupal 8 is unable to run

"$PHP5PATH"php bin/cli.php -e System -a flush --triggers 1 --session 1 

due to race conditions - esp around symphony components

We can avoid this flag by calling setup.sh from buildkit with all flags except that ie.

    if [ -e "xml" -D -g -s -d -e "bin/setup.sh" ];

instead of
    if [ -e "xml" -a -e "bin/setup.sh" ]; then

My take on this is the only think possibly lost is calling build menu?

So, options are
1) always call with the above flags rather than -a
2) figure out some d8 conditional
3) fork the install civicrm function in civibuild.lib.sh, much like we have the drupal_install

We might still need to call the system.flush - but in drupal at least we can do using drush.

**Comment by totten** [comment]
FWIW, I think there's some kind of typo in your example; 

```diff
-if [ -e "xml" -a -e "bin/setup.sh" ]; then
+if [ -e "xml" -D -g -s -d -e "bin/setup.sh" ];
   env SITE_ID="$SITE_ID" bash ./bin/setup.sh
```

The args should be part of the subsequent call to bin/setup.sh -- not the conditional. (Note that "`-a -e foo`" means "and exists file foo".)

IMHO, approach 2 sounds better in . Within `bin/setup.sh`, change 

```bash
"$PHP5PATH"php bin/cli.php -e System -a flush --triggers 1 --session 1
```

to something like

```bash
case "$GENCODE_CMS" in
  [Dd]rupal*)
    drush cvapi system.flush triggers=1 session=1
    ;;

  *)
    "$PHP5PATH"php bin/cli.php -e System -a flush --triggers 1 --session 1
    ;;

esac
```

**Comment by totten** [comment]
I believe @twomice found a resolution for this while preparing the `drupal8-clean` config.
