### ISSUE TITLE
civi-download-tools fails when getting dependencies with npm on default Debian

### ISSUE THREAD

**Issue by openbrian** [civicrm/civicrm-buildkit#177]
If the OS has npm, getting dependencies fails like this.  I'll submit a PR in a minute.

symfony/console suggests installing symfony/event-dispatcher ()
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.0.5)
phpunit/phpunit suggests installing phpunit/php-invoker (>=1.1.0,<1.2.0)
pear/console_table suggests installing pear/Console_Color (>=0.0.4)
symfony/templating suggests installing psr/log (For using debug logging in loaders)
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
wp-cli/wp-cli suggests installing psy/psysh (Enhanced `wp shell` functionality)
Generating autoload files
npm WARN optional dep failed, continuing fsevents@0.3.8
 
> phantomjs@1.9.18 install /opt/buildkit/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
> node install.js

sh: 1: node: not found

**Comment by totten** [comment]
Merged change. Thanks!
