### ISSUE TITLE
cividist - Allow an ENV variable to determine which tarballs to generate

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/civicrm-buildkit#190]
I'm just looking into setting up the script to generate 1) only drupal 7 & 2) drupal 6 & 7 but not Joomla & WP in 2 different setups.

I know we can pass in things like `env GIT_REMOTE=fuzion` - are you open to a patch that would allow
`env CMS_LIST=drupal6,drupal`

I'm also mulling over the fact that we want to untar the tarball & commit to a deployment branch - possibly that would look somewhat similar in terms of using an env to do it - or perhaps it just needs to be in a wrapper script that may or may not be accepted into the buildkit repo

**Comment by totten** [comment]
Yeah, I think doing an env variable would fit with the general style/usage of the `cividist`.

You might find it easiest to plugin at the call to `distmaker` and just pass through the arguments.

https://github.com/civicrm/civicrm-buildkit/blob/master/bin/cividist

e.g. `CMS_LIST=${CMS_LIST:-all}` (circa line 10) and `distmaker ${CMS_LIST}` (circa line 117).

**Comment by eileenmcnaughton** [comment]
Thanks I'll take a look - also there is a request to not have a tarball generated - but for it to output to a directory

OUTPUTPATH='/my/path' make sense? Would we then have OUTPUT_TARBALL=false - or do you have a more elegant idea?

**Comment by totten** [comment]
That's a bit more dicey -- all the distmaker scripts are geared toward building up the tarballs/zipfiles, so you'd have to patch several items in distmaker. The simplest approaches are either:

 * Don't use cividist or distmaker. Just use `gitify` or `drush make` (and then `rm -rf .git`)
 * Let cividist/distmaker create the tarballs... then extract them.

However, I don't really understand the use-case for that, so maybe I'm missing something.

**Comment by eileenmcnaughton** [comment]
On IRC we discussed adding another dist type - e.g we have

./distmaker d5" (for drupal+php5 tarballs) 

& could add  "./distmaker d5_dir"

Which would be callable using $DM_LIST as an env var
