### ISSUE TITLE
Create wp-demo master fails due to new directory structure

### ISSUE THREAD

**Issue by kcristiano** [civicrm/civicrm-buildkit#191]
In app/config/wp-demo/install.sh Paths are set hardcoded -- https://github.com/civicrm/civicrm-buildkit/blob/master/app/config/wp-demo/install.sh#L16

Due to WP installer changes the paths for v4.7.alpha4+ should be:
ln 21:
```
CIVI_SETTINGS="${WEB_ROOT}/wp-content/uploads/civicrm/civicrm.settings.php"
CIVI_FILES="${WEB_ROOT}/wp-content/uploads/civicrm"
CIVI_EXT_DIR="${WEB_ROOT}/wp-content/uploads/civicrm/ext"
CIVI_EXT_URL="${CMS_URL}/wp-content/uploads/civicrm/ext"
```
Obviously this should be conditional based on the --civi-ver flag.

I can attempt a patch, however not sure when I will get to it, so I am posting here for now.

**Comment by kcristiano** [comment]
https://github.com/civicrm/civicrm-buildkit/pull/194

This checks if master and if so uses new directory structure.  May need update once 4.7 branch is created as that (plus master) will be the branches to check for.  Did not test less than or equal to 4.6, biut thinking now that may be better.

Also pushed my fix for the annoying WP TimeZone notice -- sets WP TimeZone based on php's Time Zone.  This has been workig for me for quite some time now.

**Comment by colemanw** [comment]
Agree `<= 4.6` would be better.

**Comment by kcristiano** [comment]
@colemanw Agree that `<= 4.6` is better, however I have tested this and all combinations I can try and they all fail.  `<= "4.6"` `-le 4.6` `/<= "4.6"` `/< "4.7"` all fail.  Most fail building 4.6, `if [ "$CIVI_VERSION" \< "4.7" ]; then` works for 4.6 and 4.5, but not master.

The only consistent check that I can get is `=`  I must be doing something wrong and will look at later.  If you have any suggestions, I'd be happy to try tonight.

**Comment by kcristiano** [comment]
Updated https://github.com/civicrm/civicrm-buildkit/pull/194  

decided on `if [ "$CIVI_VERSION" = "master" ] || [ "$CIVI_VERSION" \> "4.6" ]`   This works for master, 4.6 4.5 and should handle 4.7 and beyond.
