### ISSUE TITLE
Vagrant - changes I needed to make

### ISSUE THREAD

**Issue by JohnFF** [civicrm/civicrm-buildkit#199]
Hi - love this!

I have the following feedback WRT using vagrant:
had to comment out server setting config.vm.network :private_network, ip: "192.168.168.10"

Need to install the following packages for precise32-standalone (sudo apt-get)
mcrypt
php5-mcrypt
drush

After these need to run:
1. civi-download-tools

2. Then this:
sudo apt-get purge nodejs npm
curl -sL https://deb.nodesource.com/setup | sudo bash -
sudo apt-get install -y nodejs

buildkit doesn't add the drupal entry to the apache conf files
Change apache virtualhost to enable htaccess overrides
        <Directory />
                Options FollowSymLinks
                AllowOverride All
        </Directory>
        <Directory /opt/buildkit/build/mytestbuild>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
        </Directory>

Then:
CiviCRM does not have permission to write temp files in /opt/buildkit/build/mytestbuild/sites/default/files/civicrm/templates_c/en_US/

**Comment by totten** [comment]
1. Oooo, does this there's a PR somewhere in the future?  :)

2. Do agree that there are missing packages now (nodejs and maybe a few php extensions). 

3. `drush` should be downloaded automatically as part of `civi-download-tools`. If it's missing, check that the files show up in `/opt/buildkit/vendor` and `/opt/buildkit/bin` and that the PATH is updated (`/etc/profile.d/civicrm_project.sh`).

4. Removing the hard-coded IP address would be awesome. Does each user need to assign an IP explicitly, or does vagrant assign one automatically?

5. Re: permissions, not sure if this helps, but for background... note the last step in:

https://github.com/civicrm/civicrm-buildkit/blob/0a5436e5b69f547c8bf30b7b84e71c37591e2edd/vagrant/precise32-standalone/bootstrap.sh#L90

which sets the `perm_type` to `linuxAcl`.  There's some more discussion about `perm_type` at 
https://github.com/totten/amp/blob/master/doc/perm.md . Basically, the idea is that two users (the current user, `vagrant`, and the httpd user, `www-data`) are both given sticky, recursive permissions to the Drupal datadir (`/opt/buildkit/build/mytestbuild/sites/default/files`). These permissions are assigned when running `civibuild`.

FWIW, the most common problems when using `linuxAcl`:
 * The local system isn't configured ACLs.(Follow links from perm.md for details)
 * The `civibuild` and `amp config` commands should *not* run as `root`; they should run as the regular user (eg `vagrant`). You won't get the right ACLs if running as `root`.

**Comment by totten** [comment]
Looks like we haven't had any follow-up on this. There's another project, https://github.com/civicrm/civicrm-buildkit-vagrant , which is derived from WordPress's "VVV" project and should be more robust.
