### ISSUE TITLE
Sourceforge is an unreliable source for civix

### ISSUE THREAD

**Issue by ejegg** [civicrm/civicrm-buildkit#219]
Sourceforge has been 'temporarily in static offline mode' all morning. They've never been the best hosting service, and I'm worried about their future given the Slashdot layoffs after being sold by Dice.

**Comment by ejegg** [comment]
Pull request: #220

**Comment by totten** [comment]
Yeah, PR takes longer.

There's a batch of these tools for which I'd like to change the release process, so it makes sense to do them at once. I'll setup Jenkins to publish civix tarballs via download.civicrm.org.

**Comment by totten** [comment]
Updated Jenkins to publish civix tarballs automatically, and updated civi-download-tools to use those tarballs.
