### ISSUE TITLE
Feature request: buildkit install without using amp

### ISSUE THREAD

**Issue by djcf** [civicrm/civicrm-buildkit#224]
Hello!

I have been experimenting with creating docker containers for CiviCRM which implement the docker principles of composerability, automateability, and so on, and of course the best way to programmatically install CiviCRM is with buildkit. My most recent attempt seems to fit the bill -- it uses separate containers for the web and database servers, which can be swapped out by the administrator at will. I hope there will be some interest in it from the Civi community, since a lot of members seem to be interested in using containers to manage their installations. You can see the results of my attempts here: https://github.com/djcf/civicrm-docker/ I believe the docker design patterns it employs are quite sound, and I hope it might be useful to someone.

In these circumstances, its useful to be able to use the buildkit tools 'civibuild download' and 'civibuild install' to programmatically configure the Civi instance, however it is not desireable to use the buildkit tools to configure the vhost, the web server, or the database server, since in this circumstance we use docker to do that. With the rise of composeable infrastructures, its easy to imagine this scenario might crop up with other tools in the future.

My feature request is simple: a way to use the buildkit install scripts (drupal-clean, backdrop-demo, etc.) without also using amp. My docker container does this at runtime with two simple hacks. Firstly, it removes amp_install() from the install script[1]. Then, because amp sets up environment variables which are now lost, and which, in any case, are managed by the docker daemon (following the third principle of the 12-factor application[2]), it then re-loads those variables back into the build environment on line 728 of src/civibuild.lib.sh after they had been sanitised[3].

Do  you think it might be useful for other users to accommodate such a feature in future releases?

You are busy. Thank you for taking the time to read this feature request.

Daniel

1: https://github.com/djcf/civicrm-docker/blob/master/build/install.sh line 48: sed -i 's/amp_install//g' /buildkit/app/config/$SITE_TYPE/install.sh
2: http://12factor.net/config
3: https://github.com/djcf/civicrm-docker/blob/master/build/install.sh line 78: sed -i 's/function drupal_install() {/function drupal_install() {\n  source \/buildkit\/install.conf/g' /buildkit/src/civibuild.lib.sh

**Comment by ginkgomzd** [comment]
I think it would be helpful to start a doc (etherpad/google/wiki) that articulates what buildkit is doing within the scope you are talking about. I then it will become trivial to borrow those parts of the script or find better ways to implement them.

I will be happy to pitch in if someone else is facilitating as I've been meaning to get to this for some time.

**Comment by totten** [comment]
Hey, that's really cool that you're building composable Docker containers. :)

For skipping `amp`, there are a few ways to formulate this. Maybe all of them are good, but just to see if anything provokes a reaction/idea, what do you think of either:

 1. You could implement a custom `amp` command. As you mentioned, `amp` basically just exports some variables. (Most of the complexity in `amp` is for adapting to different runtime environments. If you know the exact environment already, then it would pretty simple.) Pseudocode+commentary: https://gist.github.com/totten/1d041721d31e398e2345 
 2. We could add some more options to make `amp create` a nullop, e.g. `amp config:set --httpd_type=none  --db_type=none --perm_type=none`. (It already supports `none` for `httpd_type` and `perm_type`, but it would need a patch for `db_type`. )

**Comment by djcf** [comment]
First off, thanks for the excellent responses. I am pleased to see there is interest in composable docker images :-)

I'm also sorry for not being more on the ball with replying to this issue. In the short-term we are now quite behind with the project to implement CiviCRM where I work, but in the longer-term this an issue I would like to commit to assisting with.

Thank you for your thoughts @totten . Those are both great courses of action. I believe I will be following your pseudocode to implement a custom amp command in the next release of my docker container. It's a great way to do it!

For other docker devs however, I would imagine altering the buildkit itself to allow configuration such that amp create becomes a nullop might be the best way forward.

Thanks again for your interest!

**Comment by totten** [comment]
Recap:
 * `buildkit` as a whole doesn't need `amp`, but `civibuild` specifically does.
 * djcf seemed to like the idea of custom `amp` script, which is flexible and doesn't need any changes here.
