### ISSUE TITLE
Better document steps to set up cividist

### ISSUE THREAD

**Issue by xurizaemon** [civicrm/civicrm-buildkit#228]
Currently `civibuild` drops out with 

> Please prepare a 'dist' folder using buildkit and run the command within that folder.

I'd like to better document what needs doing here - there's no obvious `civibuild` command.

As far as I can tell -

* Create a directory called `default` (?)
* Create a directory `out` for tarballs to go to
* Create a directory `web` for the webroot to point to
* Clone repos in `src/` (see https://github.com/civicrm/civicrm-buildkit/blob/master/doc/cividist.md for layout - civicrm-core and then checkouts of civicrm-wordpress, civicrm-drupal, civicrm-packages, civicrm-joomla contained)

```
.
├── default
├── out
│   ├── config
│   ├── gen
│   ├── tar
│   └── tmp
├── src
│   ├── CRM
│   ├── Civi
│   ├── WordPress
│   ├── ang
│   ├── api
│   ├── bin
│   ├── bower_components
│   ├── css
│   ├── distmaker
│   ├── drupal
│   ├── extern
│   ├── i
│   ├── install
│   ├── joomla
│   ├── js
│   ├── l10n
│   ├── node_modules
│   ├── packages
│   ├── settings
│   ├── sql
│   ├── templates
│   ├── tests
│   ├── tools
│   ├── vendor
│   └── xml
└── web
    ├── by-date
    └── by-hash
```

**Comment by xurizaemon** [comment]
```
cd dist
mkdir default out web
git clone https://github.com/civicrm/civicrm-core.git src
git clone https://github.com/civicrm/civicrm-packages.git src/packages
git clone https://github.com/civicrm/civicrm-drupal.git src/drupal
git clone https://github.com/civicrm/civicrm-joomla.git src/joomla
git clone https://github.com/civicrm/civicrm-wordpress.git src/WordPress
```

**Comment by xurizaemon** [comment]
@totten is there a packaged command for this, or docs somewhere?

My proposal is we add some pointer from the error message to get people to the right next steps.

**Comment by totten** [comment]
Agree that it makes sense to give a better error message.

The command to setup that source tree is `civibuild create dist --url http://dist.localhost` . It should be mentioned as the first step in `cividist.md` and the `cividist` default help-screen.

Could you have the command link to cividist.md instead of the issue?

**Comment by totten** [comment]
Adapted 674928db262e9b3a42873004183743ba2a8fcff7 to form  3f8d0f5cf58608220407a36c1786323f01af4ba9
