### ISSUE TITLE
wpmaster: wordpress-importer plugin not found

### ISSUE THREAD

**Issue by AbdealiJK** [civicrm/civicrm-buildkit#237]
I am trying to create a dev environment of civi + wordpress on my computer.
Note: I was able to create a drupal + civi dev env earlier.

I'm running the command `civibuild create wpmaster --url http://wpmaster.localhost --admin-pass <pass>`

I seem to hit a snag when civibuild tries to download the wordpress plugin `wordpress-importer`. It says the plugin could not be found:
```
...
....
++ wp rewrite flush --hard
Success: Rewrite rules flushed.
++ wp plugin install wordpress-importer --activate
Warning: wordpress-importer: An unexpected error occurred. Something may be wrong with WordPress.org or this server&#8217;s configuration. If you continue to have problems, please try the <a href="https://wordpress.org/support/">support forums</a>.
Activating 'wordpress-importer'...
Warning: The 'wordpress-importer' plugin could not be found.
++ wp import /home/ajk/buildkit/app/config/wp-demo/civicrm-wordpress.xml --authors=create
Error: WordPress Importer needs to be installed. Try 'wp plugin install wordpress-importer --activate'.
```

I tried going into `~/buildkit/build/wpmaster/wp-content/plugins/civicrm/civicrm` and running the command, but it keeps giving the same error. I'm not sure what I can do to debug this (I haven't used wp-cli before)

**Comment by kcristiano** [comment]
I just ran this on an updated buildkit without error.   wp-cli can fail if openssl is out of date of the curl library does not support ssl.   Just to be sure it's not a one-off can you try this `wp plugin install civicrm-admin-utilities` and see if that returns any errors?

**Comment by AbdealiJK** [comment]
Hi @kcristiano Thanks for the reply :)
I tried installing `civicrm-admin-utilities` and got the same issue. It does seem to be a wp-cli error.

I'll check out how to solve this, as it's not a civicrm issue I'm closing this

**Comment by AbdealiJK** [comment]
Just an FYI for people who get the same issue:
https://wordpress.org/support/topic/cannot-install-plugins-unexpected-http-error solves the issue
They recommend changing the timeout in `wp-admin/includes/plugin-install.php` for the function `wp_remote_post()` from 15 to 60.
For some weird reason if this is done, the page loads within 2-3 seconds ... (Not sure why it timed out in the first place)

**Comment by kcristiano** [comment]
I would not recommend changing a core file, it will be overwritten on update and can have unintended consequences.   If you have this issue, I'd look to your server config first to see why it's failing for you.
