### ISSUE TITLE
get-buildkit.sh lost

### ISSUE THREAD

**Issue by saurabhbatra96** [civicrm/civicrm-buildkit#285]
I believe that https://civicrm.org/get-buildkit.sh (referred here: https://github.com/civicrm/civicrm-buildkit/blob/master/doc/download-ubuntu.md) was lost when the site was overhauled.

**Comment by totten** [comment]
Oooph, thanks. Looking.

**Comment by totten** [comment]
Fixed.

Seems like the Drupal `redirect` module isn't working in the new config. Not sure why - but worked around it by adding this to the nginx config -- https://github.com/civicrm/civicrm-org-site/commit/dde4a087164c29d45479f8bd3900735b07b65045
