### ISSUE TITLE
auto-branch bash script

### ISSUE THREAD

**Issue by xurizaemon** [civicrm/civicrm-buildkit#290]
From example in #155, a working implementation.

RM11632

**Comment by xurizaemon** [comment]
Something bothers me about the trailing hyphens on these lines ... but it works OK. Just looks bothersome.

    do_auto_branch "backdrop" 1.x-
    do_auto_branch "drupal" 7.x-
    do_auto_branch "drupal" 6.x-

**Comment by totten** [comment]
Added more feedback on #291.
