### ISSUE TITLE
extract `civichecksytem` script from `civi-download-tools`

### ISSUE THREAD

**Issue by ErichBSchulz** [civicrm/civicrm-buildkit#293]
I'm working on dockerising `civi-download-tools`

it contains a series of useful system - Lines 423-444 and 568-590 of [this version](https://github.com/civicrm/civicrm-buildkit/blob/7641b2ae6109225b24fb7e25f68d57a8f8493e29/bin/civi-download-tools)

It seems to me that this would be best and very useful as a standalone bash script.

What do you think?

Possible with a mode argument? `full|essential`

`civichecksytem full` or `civichecksytem essential`

it would be good to include version checks as well (but that would be another day!)

**Comment by totten** [comment]
@ErichBSchulz As a general matter, I like breaking things into smaller pieces.

The main issue is that we publish this instruction:

```
curl -Ls https://civicrm.org/get-buildkit.sh | bash -s -- --full --dir ~/buildkit
```

The URL for `get-buildkit.sh` is really just an alias to `civi-download-tools`, so I'm concerned that splitting it would break that use-case.

I think there are a couple options for how to get it extracted:
 * Keep it as one command, but accept an option to *only* run checks, e.g. `--check-only` or `--dry-run` or `--test` or somesuch.
 * Split the command into multiple files, but write build script to publish a combined file.
