### ISSUE TITLE
clarify required permission

### ISSUE THREAD

**Issue by ErichBSchulz** [civicrm/civicrm-buildkit#294]
It seems to be the case that civibuild needs to be run as a user who is not root but who has sudo.

It maybe helpful to say this in the README?

(happy to do a patch if you like)

**Comment by totten** [comment]
> It seems to be the case that civibuild needs to be run as a user who is not root but who has sudo.

Yup, that's generally true.

FWIW, it's mentioned in https://github.com/civicrm/civicrm-buildkit/blob/master/doc/download-ubuntu.md -- maybe you could also document it in https://github.com/civicrm/civicrm-buildkit/blob/master/doc/download-manual.md ?

(To be precise, though... going with a `sudo`-empowered user is the path of least-resistance on most systems. However, `amp`/`civibuild` were designed to work in unprivileged modes. For example, on `test-ubu1204-5.civicrm.org`, we use `amp config:set --hosts_type=none --httpd_type=none`; all the builds are exposed over HTTP using a combination of [dynamic vhosts](https://httpd.apache.org/docs/2.2/vhosts/mass.html) and wildcard DNS. But that's usually more configuration work. In most stock Linux system, the easiest way to manipulate the httpd and the resolver is via `sudo`.)

**Comment by ErichBSchulz** [comment]
I'm thinking here could be the place to mention it:

https://github.com/civicrm/civicrm-buildkit/blob/master/doc/civibuild.md

I came unstuck because I got the tools installed ok as root but then ended up needing to be "non-root with sudo" to get my civibuild to execute

Something along the lines of?:

> "In order to keep the various installation tools happy, but also enable `civibuild` to modify system settings, you must execute `civibuild` as a non-root user who has `sudo` permission."

**Comment by totten** [comment]
How about under "Your First Build", a second "Tip":

> Tip: Execute `civibuild` as a non-root user who has `sudo` permission. This will ensure that new files are owned by a regular user, and it enables `civibuild` to restart Apache or edit `/etc/hosts`.

**Comment by totten** [comment]
See d0dd69aec1e
