### ISSUE TITLE
Unable to download with ./bin/civi-download-tools

### ISSUE THREAD

**Issue by olyjosh** [civicrm/civicrm-buildkit#297]
I'm getting the below message from terminal after issuing ./bin/civi-download-tools on OS X Sierra

curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

**Comment by xurizaemon** [comment]
Can you give details of which download command failed? There is hopefully info in the output immediately before the error you saw.

Could also be helpful to give info of your PHP build, eg "homebrew using libressl" etc. I think there are issues with *some* PHP build combos and some CA chains.

Once you find the failing download command is `curl` or `wget` or `php` or ... then you might be able to debug further and give even more info?

**Comment by olyjosh** [comment]
The whole message looks like this 

```
**Olyjoshs-MBP:buildkit olyjosh$ ./bin/civi-download-tools**
[[Download composer]]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by xurizaemon** [comment]
OK, so you are [here](https://github.com/civicrm/civicrm-buildkit/blob/master/bin/civi-download-tools#L476) when this happens (see also [`download_url`](https://github.com/civicrm/civicrm-buildkit/blob/master/bin/civi-download-tools#L78)).

From the error message we can see your system uses `curl`, so this isn't strictly a civi-download-tools error IMO - the problem is that your OSX `curl` is not able to validate SSL provided by the site at https://getcomposer.org/ ... there are similar issues eg composer/composer#5519 and composer/composer#2798 which may solve your problems.

Can you give the output of these three commands please?

`which curl` (are you using OSX system curl, or something else?)

`curl --version` (let's see what your curl has to say about itself)

`curl -v -L -o /dev/null https://getcomposer.org/` (what curl says when it talks to getcomposer.org)

Random thoughts:

* Did you upgrade to OSX Sierra, and is it possible your system has an outdated version of curl, or one with no SSL support?
* Are the installed SSL certificates customised? Could a custom version of curl installed be unable to read those available on OSX Sierra?
* Are you able to talk to other SSL sites using curl as expected? (eg `curl --head https://google.com`)

**Comment by olyjosh** [comment]
@xurizaemon, Yes I am using the OSX system curl

**curl --version is** response:
> curl 7.49.1 (x86_64-apple-darwin16.0) libcurl/7.49.1 SecureTransport zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets 

**curl -v -L -o /dev/null https://getcomposer.org/** response:
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 87.98.253.108...
* Connected to getcomposer.org (87.98.253.108) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: getcomposer.org
* Server certificate: DigiCert SHA2 Secure Server CA
* Server certificate: DigiCert Global Root CA
> GET / HTTP/1.1
> Host: getcomposer.org
> User-Agent: curl/7.49.1
> Accept: */*
> 
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0< HTTP/1.1 200 OK
< Server: nginx
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept-Encoding
< Cache-Control: no-cache
< Strict-Transport-Security: max-age=31104000
< Date: Tue, 07 Feb 2017 07:10:17 GMT
< 
{ [2449 bytes data]
100  2437    0  2437    0     0   2010      0 --:--:--  0:00:01 --:--:--  2010
* Connection #0 to host getcomposer.org left intact`

I upgraded to OSX Sierra. I think its support ssl since it was able to connect to other ssl site with curl -v --head https://google.com

**Comment by xurizaemon** [comment]
Hmmm, your curl talks to that site fine, with SSL ...

Next step would be to modify the command in download_url to get more info about why it's not working in that script.

Let us know how you get along?

**Comment by olyjosh** [comment]
So how do i go about this

**Comment by olyjosh** [comment]
Running this command **curl -v -L -o /dev/null https://getcomposer.org/** again now respond with 

```
* About to connect() to getcomposer.org port 443 (#0)
*   Trying 87.98.253.108...
* Adding handle: conn: 0x101000000
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x101000000) send_pipe: 1, recv_pipe: 0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to getcomposer.org (87.98.253.108) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: /Applications/XAMPP/xamppfiles/share/curl/curl-ca-bundle.crt
  CApath: none
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Server hello (2):
{ [data not shown]
* SSLv3, TLS handshake, CERT (11):
{ [data not shown]
* SSLv3, TLS alert, Server hello (2):
} [data not shown]
* SSL certificate problem: unable to get local issuer certificate
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by xurizaemon** [comment]
Looks like some issue with Xammp certs (possibly Xammp curl?)

Add `-k` to the download_url command to work around this, or resolve the
cert issue.

Looks like there are a few search results for Xammp curl ssl issues but
don't want to lead you astray with a wrong link :)

**Comment by xurizaemon** [comment]
Or maybe ensure that civi-download-tools picks up on the "good" curl in /usr/bin and not that Xammp one. (Set path to executable in the script.)

**Comment by xurizaemon** [comment]
... or the right CAfile! (Sorry, 📱!)

**Comment by olyjosh** [comment]
Adding "-k" option shows that there is no such option on civic-download-tools.
I finally get to know that exporting bin directory of xamppfile like this **PATH=/opt/local/bin:/opt/local/sbin:/Applications/xampp/xamppfiles/bin:$PATH** makes xampp curl to overide the system curl. So I moved the curl and curl-config files from the /Applications/xampp/xamppfiles/bin to be able to run civic-download-tools command. The curl that comes with the version of xampp 5.8.6 that I'm using, has problem with ssl. This is the current work around base on your suggestion above. Thanks

Regards

**Comment by olyjosh** [comment]
This is ssl problem from xampp curl.

**Comment by xurizaemon** [comment]
Great. Other possible for this could have been -

* Updating XAMMP (probably?)
* Install updated certificates from the URL linked in your initial question (see [this](https://forum.dokuwiki.org/thread/12273) or [this](https://www.ostraining.com/blog/drupal/drupal-xampp-curl-error-60/))
* Hardcoding paths in `download_url` to use the system provided `curl` which has functional SSL

Thanks for reporting back on what worked for you!

**Comment by Base29** [comment]
Hello Guys ... Starting fresh with CiviCRM Extension development ... following the instruction on the site to install the tools using `civi-download-tools` command but I am facing an issue ... please see this [Screenshot](http://prntscr.com/fy8f83) ... I am not sure how to resolve this ... any suggestions ... Thanks

**Comment by PalanteJon** [comment]
@Base29 There are several suggestions on how to fix this earlier in the thread - in particular [here](https://github.com/civicrm/civicrm-buildkit/issues/297#issuecomment-277862530).  Since this is a composer issue, you may want to try to resolve it in their Github issue queue.

Also, to receive better help in the future, consider the following suggestions:
* Open your own issue instead of jumping on an existing issue thread.
* Tell us what you've already tried that hasn't worked.
