### ISSUE TITLE
civibuild - assume http:// for --url if not present

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-buildkit#300]
If I run `civibuild create foo --url foo.local --type drupal-demo` it fails with the error message "Failed to parse URL: foo.local". Eventually I figured out that I needed to use `--url http://foo.local`, but it would be nice if `civibuild` could be smarter about this and accept `--url foo.local` as well.

**Comment by totten** [comment]
*Background*: The `--url` is basically passed through to `amp`. In the interests of mental health, I'd just that the internal format of the `Amp\Instance::$url` property should still be a well-formed URL.

*Suggestion*: You can add some kind of normalization during the input process, e.g. either:
 * [civibuild.parse.sh](https://github.com/civicrm/civicrm-buildkit/blob/58a45a149db96c32b165a65c73d6620c0483f98c/src/civibuild.parse.sh#L249)
 * [Amp/Command/CreateCommand.php](https://github.com/amp-cli/amp/blob/0.3.8/src/Amp/Command/CreateCommand.php#L74)

Calling normalization in `civibuild.parse.sh` has the advantage that we wind up with consistent config files (i.e. `buildkit/build/foo.sh` contains a real URL). Patching this file involves fewer layers, but it needs to be written in `bash`.

Calling normalization  in `Amp/Command/CreateCommand.php` has the advantage that (other/theoretical/non-civibuild) callers would benefit have the same normalization. Patching this file can use more familiar PHP syntax, but the dev/test workflow is more complicated (e.g. after editing `amp` code, [build a new PHAR](https://github.com/amp-cli/amp#build) and copy it to `buildkit/bin/amp`).

Either approach is acceptable/mergeable IMHO.

**Comment by devarun** [comment]
@totten @seanmadsen 

Submitted patch for this.

**Comment by totten** [comment]
Thanks again. I've merged the change to `amp` and updated the copy of `amp` used in buildkit.
