### ISSUE TITLE
outdated version of node/npm on Debian jessie leads to difficult mess

### ISSUE THREAD

**Issue by jmcclelland** [civicrm/civicrm-buildkit#315]
protractor has a dependency that uses the @ syntax, which npm version 1.4.21 can't parse, resulting in build failures (see debian bug:  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=794890).

However, installing a new version of nodejs manually (per https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) causes civi-download-tools to fail.

civi-download-tools fails because it detects jessie and tries to install npm and nodejs-legacy, however, the newer version of nodejs identifies these packages as "conflicts."

**Comment by jmcclelland** [comment]
I think the proper fix is to run the nodejs setup script, then add nodejs as a package to install and remove npm and nodejs-legacy. 

Thoughts?

**Comment by PalanteJon** [comment]
This is the approach taken when installing Ubuntu 12.04, and #318 is the same problem but for Ubuntu 14.04.  I could bikeshed the approach in #318, but it DOES work.  If @totten merges #318, I would take that as the go-ahead to submit a similar fix for Jessie.

**Comment by jmcclelland** [comment]
Thanks Jon for the reference.

**Comment by MikeyMJCO** [comment]
# Problem

**OS:** Debian Jessie 8.11.0
**Steps:**
 - Updated Jessie (`sudo apt update`) (`sudo apt upgrade`)
 - Installed Curl (`sudo apt install curl`)
 - Ran buildkit installer (`curl -Ls https://civicrm.org/get-buildkit.sh | bash -s -- --full --dir ~/buildkit`)

**Results:**
> protractor@4.0.14: wanted

> Error: Method Not Allowed

# Resolution

1. Remove nodejs-legacy and npm (`sudo apt remove nodejs-legacy npm`)
2. Install nodejs v8 from nodesource (`wget -O- https://deb.nodesource.com/setup_8.x | sudo -E bash -`)
3. Run `sudo apt install nodejs`
4. Re-run civi-download-tools (`cd ~/buildkit && ./civi-download-tools`)
5. Profit!

I'll raise a PR to get this fixed today.

**Comment by MikeyMJCO** [comment]
PR is up #433
