### ISSUE TITLE
can't run unit tests do to empty string being passed as port

### ISSUE THREAD

**Issue by jmcclelland** [civicrm/civicrm-buildkit#316]
I get the error:

[nativecode=mysqli_connect() expects parameter 5 to be long, string given]

However, I can fix the problem by removing the trailing : after localhost in /var/www/civicrm/civicrm-buildkit/build/mycivi.sh

In other words, from:

    TEST_DB_DSN="mysql://mycivitest_b9rn3:xxxxxx@localhost:/mycivitest_b9rn3?new_link=true"

To:

    TEST_DB_DSN="mysql://mycivitest_b9rn3:xxxxxx@localhost/mycivitest_b9rn3?new_link=true"

**Comment by seamuslee001** [comment]
@jmcclelland have you tried re-building recently to see if there is still the issue?

**Comment by jmcclelland** [comment]
After an enormous amount of yak shaving (my civicrmbuild environment now runs under debian stretch) I can confirm that this bug is still in place. My build environment is fully documented here: https://github.com/progressivetech/docker-civicrm-buildkit

**Comment by totten** [comment]
Would it be possible to just pass the port number in https://github.com/progressivetech/docker-civicrm-buildkit/blob/master/civicrm-buildkit-setup#L32 ?

**Comment by jmcclelland** [comment]
Yes - that does the trick. I thought this might affect other people, but if I'm the only one, let's close now that I've made the recommended change in my docker image.
