### ISSUE TITLE
WP script fails when soft link cannot be created

### ISSUE THREAD

**Issue by kcristiano** [civicrm/civicrm-buildkit#321]
Related:  https://github.com/civicrm/civicrm-buildkit-vagrant/issues/21

At the St Louis sprint, some uses experienced issues with `civibuild create wp-master`  Traced this to creating a soft link here https://github.com/civicrm/civicrm-buildkit/blob/master/app/config/wp-demo/download.sh#L15

This appears to be intermittent, and looks to be permissions related to running Virtual Box on Windows.

As wp-cli does not need  yml file in each site, for the Vagrant buildkit we can add  a single yml file at `~/.wp-cli/config.yml`  see theb docs:
https://make.wordpress.org/cli/handbook/config/#config-files

We will need a corresponding patch to buildkit since the fact that we can create a single yml here will not address the code that shows the error.   Perhaps we should test to see if `~/.wp-cli/config.yml` exists before creating the soft link.

**Comment by totten** [comment]
Related: #358
