### ISSUE TITLE
Move documentation from buildkit.c.o to Dev Guide

### ISSUE THREAD

**Issue by seancolsen** [civicrm/civicrm-buildkit#333]
The site https://buildkit.civicrm.org currently offers documentation for buildkit. It's a great site, but I would like to migrate this docs content to the Developer Guide (and take down the dedicated site) for the following reasons: 

* Content in the buildkit site is not [complete](http://www.writethedocs.org/guide/writing/docs-principles/#complete).
* The buildkit site does a poor job making [the rest](https://docs.civicrm.org/dev/en/latest/tools/buildkit/) of the buildkit docs [discoverable](http://www.writethedocs.org/guide/writing/docs-principles/#discoverable)
* Content in the buildkit site [overlaps](http://www.writethedocs.org/guide/writing/docs-principles/#unique) with content in the Developer Guide
* It's difficult to distribute the work of maintaining documentation within the buildkit site across the people who are motivated to improve documentation *(making it hard to be [participatory](http://www.writethedocs.org/guide/writing/docs-principles/#participatory) and [current](http://www.writethedocs.org/guide/writing/docs-principles/#current))*
* The interface of the buildkit site is not [consistent](http://www.writethedocs.org/guide/writing/docs-principles/#consistent) with other CiviCRM documentation

*Though it's worth noting that the site does an excellent job of being [exemplary](http://www.writethedocs.org/guide/writing/docs-principles/#exemplary) and [beautiful](http://www.writethedocs.org/guide/writing/docs-principles/#beautiful) :slightly_smiling_face:*

Before removing the site, however, we need to reconcile the fact that there is currently still some documentation in there which does not exist elsewhere (e.g. Use Case = "Scheduled Test" or "Code Review Test"). Tim and I spoke on the phone yesterday and agreed that if/when we can create content in the Developer Guide which serves this purpose, then we can take the buildkit site down.

**Comment by dvhirst** [comment]
This makes very good sense; I'd like to see the documentation extended to support other CRMs, e.g., WordPress (primarily) and Joomla (secondary, IMO).  I expect to work through this process and will provide, as I'm able, updates to reflect the WordPress use case.

**Comment by MikeyMJCO** [comment]
This has been acted upon - good to close for someone with permissions.
