### ISSUE TITLE
Add `civibuild types` command to list available build types

### ISSUE THREAD

**Issue by seancolsen** [civicrm/civicrm-buildkit#334]
Learning about the available build types that `civibuild` offers is currently somewhat difficult. 

You can [go here](https://docs.civicrm.org/dev/en/latest/tools/civibuild/#build-types) for an easy-to-read but incomplete list. Or you can [go here](https://github.com/civicrm/civicrm-buildkit/tree/master/app/config) for a complete but hard-to-read list. Neither of those options are easy to discover when you're actually running `civibuild` from the command line. 

I propose a new command `civibuild types` which lists all the possible build types along with a description of each.

**Comment by dvhirst** [comment]
Civibuild types is very helpful.  Thanks.
