### ISSUE TITLE
Change WordPress builds to use twentyseventeen

### ISSUE THREAD

**Issue by devarun** [civicrm/civicrm-buildkit#341]
The WordPress builds [wp-empty](https://github.com/civicrm/civicrm-buildkit/blob/master/app/config/wp-empty/install.sh#L25), [wp-demo](https://github.com/civicrm/civicrm-buildkit/blob/master/app/config/wp-demo/install.sh#L51) & [wp-case](https://github.com/civicrm/civicrm-buildkit/blob/master/app/config/wp-case/install.sh#L41) are using twentythirteen theme, can we change them to use twentyseventeen, the latest theme available with WordPress.

**Comment by totten** [comment]
@kcristiano what do you think?

**Comment by kcristiano** [comment]
Any other theme, maybe, but not twentyseventeen.   I personally loathe that theme for many reasons.   

In our case as this builds our demo site http://wpmaster.demo.civicrm.org/ i want a theme that looks good with our default css and that theme is currently twentythirteen.  I just don't think our demo would look good with twentyseventeen.   

I get that twentythirteen looks old.

I do want to switch themes, I've been building our demo sites with stargazer https://wordpress.org/themes/stargazer/  and had wanted to do a fork that was set up for CiviCRM + WP

**Comment by devarun** [comment]
@totten @kcristiano 

Thanks for your inputs, I will build a demo using `stargazer` and update here, if you suggest we can build a fresh theme for CiviCRM and add it to wordpress.org repo, which can give a more customized look to demo sites and could be helpful for first time CiviCRM + WordPress users to get started.

**Comment by totten** [comment]
@devarun thanks, look forward to your update on `stargazer`.

@kcristiano @devarun Would your sense be that the stock/canonical `stargazer` would be an improvement over status quo? Or is the discussion of forking an indication that it needs some revision first?

**Comment by devarun** [comment]
@totten @kcristiano 

Today I tried the `stargazer` in my local setup, but the contribution & membership pages seemed to have minor styling problems. I though to create a demo so that you can have a look into it.

![contribution page civiwp](https://user-images.githubusercontent.com/2919476/29047594-f6aa7a7c-7be9-11e7-85ab-f66fe32aa078.png)

![membership page civiwp](https://user-images.githubusercontent.com/2919476/29047626-147571ec-7bea-11e7-9d3d-00be094dd86a.png)

**Comment by kcristiano** [comment]
@devarun @totten I agree there are styling issues.  However, I find that on almost all themes.  

The reason I don't want to use the 'default' theme from WP is that is in many cases a showcase theme of new features. 

What I think is we need a base theme with customizations.   I use an extension to add the css changes I want on CiviCRM's front end.   

The latest RC showing this is at https://cv4724rc.tadpole.cc/donate/ https://cv4724rc.tadpole.cc/join/ https://cv4724rc.tadpole.cc/event-page/

Not perfect - nor is Stargazer the absolute best choice - perhaps there is a better theme to showcase CiviCRM

**Comment by kcristiano** [comment]
@totten any thoughts on changing the theme used by buildkit?   2013 does look dated, but we need to pick a theme that we can ensure looks good on http://wpmaster.demo.civicrm.org/

If you are interested and as this affects the demo site I'd like to get buy in before we look at getting a theme together for this.
