### ISSUE TITLE
Why do we ship with phpunit 3.7.27 in composer?

### ISSUE THREAD

**Issue by mattwire** [civicrm/civicrm-buildkit#344]
We ship a binary of phpunit4.  Why do we need 3.7.27 in composer, updating that to 4.8.21 makes remote phpunit work nicely with phpstorm.

**Comment by totten** [comment]
I don't think we need it now -- `master` uses phpunit4, and `4.6` uses its own forked copy of phpunit 3, and I think this is a holdover from the transition.

**Comment by totten** [comment]
phpunit 3.x has been removed. :) #408.
