### ISSUE TITLE
WP Version

### ISSUE THREAD

**Issue by kcristiano** [civicrm/civicrm-buildkit#359]
We are currently pulling the latest version of WP.   There is currently an issue where `wp core download` will fail on Ubuntu 14.04 and WP 4.8.2.  

Do we want to go back to managing the WP version?  I believe that would be a good idea as the releases are not too frequent.

**Comment by totten** [comment]
@kcristiano is this still a problem?

**Comment by kcristiano** [comment]
@totten I would like to up the version.   However, due to the uncertainty of v 5.0 (WP not Civi) I want to pin the version to the 4.9 branch.  

The CiviCRM Shortcode button will not be compatible with WP 5.0.  I have been waiting until there is a clear spec on what we have to do to build a block for CiviCRM in the new editor. I should be able to oppen the Jira Ticket soon (if JIRA is still around).

Would we be open to switching to a git checkout of WP?  I have done that here: https://github.com/kcristiano/civicrm-buildkit/tree/wpgit  but it's clunky due to the naming conventions of the WP git clone.

Alternatively, we can go back to latest and if/when 5.0 ships we can pin it at that point.

**Comment by totten** [comment]
Personally, I'm down with using `git` on `wp-empty`, `wp-demo`, etc. The `civicrm.org` infra shouldn't care about the branch-naming (as long as the default `civibuild` configs are decent). Several other build-types use `git` for the base dir (e.g. `backdrop-{clean,demo,empty}` and all the Symfony-based apps).

One thing, though, is that I'd change the `git clone` statement:

https://github.com/kcristiano/civicrm-buildkit/blob/wpgit/app/config/wp-demo/download.sh#L13

and use a cache of the git-repo. That should speed-up the download step. Look at these lines for an example:

https://github.com/civicrm/civicrm-buildkit/blob/master/app/config/backdrop-clean/download.sh#L7
https://github.com/civicrm/civicrm-buildkit/blob/master/app/config/backdrop-clean/download.sh#L13

**Comment by MikeyMJCO** [comment]
Would this have been fixed by #422 / #423

**Comment by kcristiano** [comment]
@MikeyMJCO Yes it was fixed.   I was able to mitigate any issues with WP 5.0 without moving to git (and an odd syntax).

I'll close this now,  thanks for the reminder
