### ISSUE TITLE
Silence which nodejs error message

### ISSUE THREAD

**Issue by michaelmcandrew** [civicrm/civicrm-buildkit#364]
https://github.com/civicrm/civicrm-buildkit/commit/09682c7c92b5f8a3b050c045956fb90631ffaa64 introduces a workaround for the node/nodejs naming issue.

An side effect of this is the printing of an error message along the lines of 

```
which: no nodejs in (/usr/local/sbin:/usr/local/bin:/usr/bin...
```

when nodejs is not found. This error message can be silenced by redirecting the error (along with the output) to /dev/null.

A minor improvement but increases our signal to noise ratio which is good for usability.

**Comment by totten** [comment]
Merged the PR. Thanks!
