### ISSUE TITLE
Add package-lock.json

### ISSUE THREAD

**Issue by michaelmcandrew** [civicrm/civicrm-buildkit#366]
[NPM 5](http://blog.npmjs.org/post/161081169345/v500) produces a package-lock.json file that should be committed to the repo. I can submit a PR for this unless you want to do so @totten (based off of some hypothetical canonical setup whose existence I am pondering).

**Comment by MikeyMJCO** [comment]
I can see the stability benefit of including a package-lock file - however given that we're mixing sources between system (`apt-get`) and composer and bower I feel that locking down one of these sources might introduce issues which are difficult to debug.

We have bknix/docker/vagrant for "canonical" environments?

**Comment by michaelmcandrew** [comment]
@totten and @MikeyMJCO - closing - feel free to open again if you feel strongly / want to take ownership.
