### ISSUE TITLE
Switch from https://buildkit.civicrm.org to https://docs.civicrm.org/dev/en/latest/tools/buildkit/

### ISSUE THREAD

**Issue by michaelmcandrew** [civicrm/civicrm-buildkit#367]
The description of this repo mentions https://buildkit.civicrm.org. Is that still being maintained or if we should update it to https://docs.civicrm.org/dev/en/latest/tools/buildkit/?

**Comment by totten** [comment]
Updated the Github link.

**Comment by totten** [comment]
Relatedly, I also added a notice at the top of `buildkit.civicrm.org` to point to the same place. https://github.com/totten/ciui/commit/1833074f57e42fb21f58f7b397fa4515c05a56a4
