### ISSUE TITLE
Consider not altering $PATH in bin/civibuild

### ISSUE THREAD

**Issue by michaelmcandrew** [civicrm/civicrm-buildkit#368]
The following lines are a belt and braces approach to ensuring that civibuild has access to the binaries that it needs:

https://github.com/civicrm/civicrm-buildkit/blob/823b193cb5618fbe42284fc9e2dfbb9e58a3ae02/bin/civibuild#L20-L21

But they prevent people who 'know better' from allowing their own versions of civibuild's tools. For example, I would like to run a forked version of amp with my own nginx config template but am unable to do so since the path is overwritten.

https://docs.civicrm.org/dev/en/latest/tools/buildkit/#path already mentions that you need to configure your $PATH correctly which is enough and less intrusive.

In the comment you wrote 'available'. If you wanted to ensure that these specific versions were used then this is a good approach. If you just want them as a backup, you could always put them at the end. Or if we decided that rtf-installation-m was the best way to go then I would advocate removing it entirely.

**Comment by totten** [comment]
Yeah, when I first added that, setting the `PATH` like this killed two birds with one stone:

 * It allows `civibuild` to work even if you don't put `buildkit/bin` in the `PATH`. (You can call `./bin/civibuild create foo`... many CLI tools support this interaction.)
 * There will be some constituency which already runs their own mix of `drush` or `wp-cli` before installing buildkit. They'd hit subtle incompatibilities if (a) you force buildkit to use their version or (b) you force them to run buildkit's version. Diagnosing such subtle incompatibilities would be... quite unintuitive.

So I landed on this approach: the user owns their command-line (they can pick/choose/prioritize PATHs however they want), and `civibuild` owns its internal processing.

The user-story you describe is a bit different -- the user tries to influence `civibuild`'s internal processing. This should actually be possible without any patches, though. The file `app/civibuild.conf` allows an admin to control the environment for `civibuild`. Just edit `app/civibuild.conf` and append `export PATH=/path/to/my/tool:$PATH`. Maybe we should add some comments/suggestions for `PATH` in `app/civibuild.conf.tmpl`?

A few more thoughts:
 * For the custom `amp` scenario, I've used a different work-around during development (e.g. `cd ~/src/amp && php -dphar.readonly=0 `which box` build  &&  /bin/cp amp.phar ~/buildkit/bin/amp`), but I can see how your approach might be desirable for a long-running fork.
 * Would you be able to de-fork `amp` if we merged https://github.com/amp-cli/amp/pull/47 ? (It should allow you to customize the template by setting `export NGINX_VHOST_TPL=/path/to/my/favorite-nginx-template.php`)

**Comment by michaelmcandrew** [comment]
@totten - yeah - that is the fix I was looking for / the underlying issue I was trying to solve.

I've checked out that branch locally and it is working for me :)

I will defer to you on the user stories you mentioned above since you have thought about it more than me.

> The file app/civibuild.conf allows an admin to control the environment for civibuild

That's nice - I was not aware of that. I would also vote for documenting it in the buildkit docs since otherwise, one might not come across `app/civibuild.conf`.

**Comment by totten** [comment]
Merged #378.

By-the-by: https://docs.civicrm.org/dev/en/latest/tools/civibuild/#settings-civibuild

**Comment by michaelmcandrew** [comment]
@totten - yeah - i went to the docs to add that before I realised it was there. I probably don't do enough doc reading.

aside / continuation of my thoughts: it has taken me a little while to grok the relationship between buildkit, civibuild and the various configuration files that are associated with them.
