### ISSUE TITLE
civicrm/packages overwritten during civibuild create

### ISSUE THREAD

**Issue by michaelmcandrew** [civicrm/civicrm-buildkit#369]
I am having a fairly hard time understanding how this drush.make.tmpl has been working for people (myself included! - it was working fine, then stopped)when libraries[civicrm] is defined after libraries[civicrmpackages] etc. When I run it, the civicrm/packages folder (and similar folders like civicrm/l10n, civicrm/drupal etc.) are overwritten when the libraries[civicrm] definition is processed. As a result, I get a PHP Warning:  require_once(Log.php): failed to open stream: No such file or directory in /var/civicrm-buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Core/Config.php on line 38 error (the file can normally be found in civicrm/packages) and civibuild create dies half way through... 

Re-arranging the order of definitions in the file so that libraries[civicrm] appears before libraries[civicrmpackages] fixes the problem for me.

I tested this with drush 7.0-dev and 8.1.15.

**Comment by michaelmcandrew** [comment]
I'm not 100% on the testing on both versions - it *might* be something that only happened for me in 81.15 but at the minute I am fairly sure it happen in both versions. I can confirm that if you like.

**Comment by totten** [comment]
I've only seen the problem on `drush8` -- with `drush` 7.0-dev, it's always worked for me.

Never-the-less, reordering it is a good idea. (I think that v7 works either way.)

**Comment by totten** [comment]
I think this was resolved by #370.
