### ISSUE TITLE
Prepare Buildkit for testing Gutenberg on WordPress

### ISSUE THREAD

**Issue by kcristiano** [civicrm/civicrm-buildkit#422]
WordPress 5.0 will be released this year.  We can guess when that will be but it should be between Late September and December 1st based on information I have.

We will need to have Buildkit prepped for testing.

- Update WP to latest stable version
- Update wp-cli to latest stable version
- Install and activate the plugin Gutenberg Ramp to allow demo sites to be built _without_ Gutenberg
- Add the Gutenberg Plugin but do not activate

related https://lab.civicrm.org/dev/wordpress/issues/3

**Comment by MikeyMJCO** [comment]
- [ ] Update WP to latest stable
- [ ] Update wp-cli to latest stable
- [ ] Install and activate Gutenberg Ramp
- [ ] Add Gutenberg Plugin (do not activate)

**Comment by MikeyMJCO** [comment]
WP-CLI is currently @ v 2.0.1 - Current stable is v 2.0.1

**Comment by kcristiano** [comment]
thanks @MikeyMJCO I forgot to close this when ﻿﻿https://github.com/civicrm/civicrm-buildkit/pull/423 was merged
