### ISSUE TITLE
Ubuntu 18.04.1 LTS (Bionic Beaver) - libssl-dev/nodejs/npm dependency hell!

### ISSUE THREAD

**Issue by MikeyMJCO** [civicrm/civicrm-buildkit#426]
Running the BuildKit installer script on Ubuntu 18.04.1 LTS doesn't work - it fails trying to resolve the conflict between the openssl libraries used by Ubuntu's `NodeJS`/`NPM` packages and the `libssl-dev` package.

# Reproduce:

On a freshly installed Ubuntu 18.04.1 box run the following:

1. `sudo apt update`
2. `sudo apt install nodejs`
3. `sudo apt install npm`
4. `sudo apt install libssl-dev`

Observe the failure to install libssl-dev due to a dependency failure.

# Workaround:

1. Install a compatible version of NodeJS/NPM from NodeSource
    - `curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -`
2. Download, **don't run**, the *get-buildkit.sh* script.
    - `wget https://civicrm.org/get-buildkit.sh`
3. Using the editor of your choice, edit the downloaded script.
    - `editor get-buildkit.sh`
4. On line **453**:
    - (`PACKAGES="acl git wget unzip zip mysql-server mysql-client php7.2-cli php7.2-imap php7.2-ldap php7.2-curl php7.2-mysql php7.2-intl php7.2-gd php7.2-dev php7.2-bcmath php7.2-mbstring php7.2-soap php7.2-zip php7.2-xml apache2 libapache2-mod-php7.2 nodejs npm php-pear libmcrypt-dev libreadline-dev"`)
    Remove **npm**:
    - (`PACKAGES="acl git wget unzip zip mysql-server mysql-client php7.2-cli php7.2-imap php7.2-ldap php7.2-curl php7.2-mysql php7.2-intl php7.2-gd php7.2-dev php7.2-bcmath php7.2-mbstring php7.2-soap php7.2-zip php7.2-xml apache2 libapache2-mod-php7.2 nodejs php-pear libmcrypt-dev libreadline-dev"`)
5. Make the script executable:
    - `chmod +x get-buildkit.sh`
6. Install BuildKit:    
   **Important** The script CANNOT be in the same directory you intend to install BuildKit to!
   - `./get-buildkit.sh --full --dir ~/buildkit`
7. Continue the usual steps from here:
   - https://docs.civicrm.org/dev/en/latest/tools/buildkit/#config
# Tips

Ubuntu 18.04.1 installs `mysql-server` using a randomly generated password. For the amp-config step (to connect to mysql) you'll need this username/password. To find it:
 - `sudo cat /etc/mysql/debian.cnf`

This will give you something like:
```cnf
# Automatically generated for Debian scripts. DO NOT TOUCH!
[client]
host     = localhost
user     = debian-sys-maint
password = AMFMMjFGLMdVpubk
socket   = /var/run/mysqld/mysqld.sock
[mysql_upgrade]
host     = localhost
user     = debian-sys-maint
password = AMFMMjFGLMdVpubk
socket   = /var/run/mysqld/mysqld.sock
```

This can then be used directly as your amp mysql_dsn:
- `mysql://debian-sys-maint:AMFMMjFGLMdVpubk@localhost:3306`

# Next Steps

If you can reproduce this behaviour *please* comment below and I'll get a PR raised - if this is just an odd edge-case which is difficult to reproduce or Hyper-V specific (both confirmed reproductions are on Hyper-V) then it's probably not worth changing get-buildkit.sh.

**Comment by MikeyMJCO** [comment]
**StackExchange Q:** https://civicrm.stackexchange.com/questions/26664/civicrm-buildkit-install-fails-on-ubuntu-18-04-1-lts/26665#26665

**Comment by navy2kq** [comment]
I did have this problem on ubuntu 18.04.1.

I tried the workaround and it went flawlessly!

Thank you Mikey!

**Comment by MikeyMJCO** [comment]
Closing - Fix is committed.
