### ISSUE TITLE
[Discuss] Deprecate EOL Ubuntu Versions

### ISSUE THREAD

**Issue by MikeyMJCO** [civicrm/civicrm-buildkit#432]
Currently BuildKit includes [specific install steps](https://github.com/civicrm/civicrm-buildkit/blob/e278123c2a5edb525a01c816283d30b882aa8fab/bin/civi-download-tools#L329) for:

## Ubuntu
 Version | Codename | Release Date | EOL Date
--------- | ------------ | -------------- | ----------
19.04 | Disco Dingo | April 2019 | January 2020
18.10 | Cosmic Cuttlefish | October 2018 | July 2019 <sup>&#x1F534;</sup>
18.04 | Bionic Beaver | April 2018 | April 2023
17.10 | Artful Aardvark | October 2017 | July 2018 <sup>&#x1F534;</sup>
17.04 | Zesty Zapus<sup>*</sup> | April 2017 | January 2018 <sup>&#x1F534;</sup>
16.10 | Yakkety Yak<sup>*</sup> | October 2016 | July 2017 <sup>&#x1F534;</sup>
16.04 | Xenial Xerus | April 2016 | April 2021
14.04 | Trusty Tahr | April 2014 | April 2019 <sup>&#x1F534;</sup>
12.04 | Precise Pangolin | April 2012 | April 2017 <sup>&#x1F534;</sup>

<sup>*</sup> = Reuses installation steps for Xenial Xerus.
<sup>&#x1F534;</sup> = Is currently EOL

## Debian
Version | Codename | Release Date | EOL Date
--------- | ------------ | -------------- | ----------
10 | Buster | July 2019 | 202x
9 | Stretch | June 2017 | 2022
8 | Jessie | April 2015 | June 2020

Should we consider dropping specific install steps for EOL Debian/Ubuntu versions?

This would mean dropping the specific installer steps for:

 - 18.10 / Cosmic
 - 17.10 / Artful
 - 17.04 / Zesty
 - 16.10 / Yakkety
 - 12.04 / Precise

If so we should also probably amend `do_system_unknown()` as follows:

``` bash
function do_system_unknown() {
  echo "ERROR: Could not identify the required system packages."
  echo ""
  echo "System specific install steps are removed when an OS release is marked EOL (Ubuntu/Debian)"
  echo "
  echo "If you want to add support for a new system, update 'get_system_installer()'"
  echo "and add a new 'do_system_*()' function."
  echo ""
  echo "If you are running Debian, install lsb-release package."
  exit 1
}
```

**Comment by JoeMurray** [comment]
+1 for direction here in terms of deprecating versions that are EOL. The downside of this is that we would be removing ease of setup for testing for these environments which are present in our ecosystem. I think we should not be expending community time on that, so I'm okay with it.

**Comment by eileenmcnaughton** [comment]
Given the above PR to drop Buster I think it would be OK to do a PR to drop the others....

**Comment by MikeyMJCO** [comment]
<3 Yay! I'm gonna raise a PR :-)

**Comment by MikeyMJCO** [comment]
PR is up.

**Comment by MikeyMJCO** [comment]
Worth noting @eileenmcnaughton that the PR you referenced didn't remove Jessie in the end because Jessie is still in LTS community support in Debian-land.

However I still think this is the right move to drop these OSes as they leave LTS or end support.

**Comment by MikeyMJCO** [comment]
As a stated policy on this - how about we do "End of LTS + 6 months" = removal from BuildKit.

**Comment by MikeyMJCO** [comment]
This would mean that end of January is the removal of Cosmic. Puts us on time for the removal of Trusty.

**Comment by eileenmcnaughton** [comment]
I agree with that - @totten ?
If so where would we document?

**Comment by MikeyMJCO** [comment]
We have BK docs on https://docs.civicrm.org/dev/en/latest/tools/buildkit

**Comment by totten** [comment]
> As a stated policy on this - how about we do "End of Life + 6 months" = removal from BuildKit.

Yup, that sounds pretty good to me.

**Comment by MikeyMJCO** [comment]
I'll PR a change to docs and readme to make that clear then :-)
