### ISSUE TITLE
Composer needs to be used...

### ISSUE THREAD

**Issue by Myrddinwylit** [civicrm/civicrm-buildkit#438]
any of the drupal8 builds that use CIVICRM the build doesn't install civicrm with Drush8 cause it has to be installed using composer.

**Comment by eileenmcnaughton** [comment]
https://github.com/civicrm/civicrm-buildkit/pull/442 relates

**Comment by MikeyMJCO** [comment]
We're now using composer in Core and Buildkit - it should in theory be possible to get a D8 build into Buildkit using Drush/Composer? @totten am I mistaken on any of this?
