### ISSUE TITLE
Include PHPUnit 7

### ISSUE THREAD

**Issue by MikeyMJCO** [civicrm/civicrm-buildkit#439]
We currently don't include a version of PHPUnit which includes PHP 7.2 compatibility. We can solve this by including PHPUnit 7 but we may also want to consider removing PHPUnit 4.

PHPUnit 5 + 7 will give us coverage of:

- PHP 5.6
- PHP 7.0
- PHP 7.1
- PHP 7.2
- PHP 7.3

**Comment by JKingsnorth** [comment]
How did that weekend go? ;] I'm running in to this error (related to the PHP7.2 incompatibility) with a fresh installation using buildkit, so it would be great to get this fixed up in buildkit out of the box with civibuild.

PHP Fatal error:  Declaration of SebastianBergmann\Comparator\DateTimeComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false) must be compatible with SebastianBergmann\Comparator\ObjectComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false, array &$processed = Array) in phar:///home/developer/buildkit/extern/phpunit4/phpunit4.phar/sebastian-comparator/DateTimeComparator.php on line 80

**Comment by MikeyMJCO** [comment]
@JKingsnorth that weekend got lost in a whole mess of stuff I can no longer recall - but this is back on my radar with a view to achieving PHP 7.3 compatibility in buildkit where possible.

**Comment by eileenmcnaughton** [comment]
@MikeyMJCO since this we fixed our tests to run with php 6  - which resolved a bunch of naming issues

**Comment by MikeyMJCO** [comment]
Awesome :-) That'll make life easier!

**Comment by MikeyMJCO** [comment]
If we get to PHP7.3+PHPUnit 7 I can add the docs-publisher build/test workflow to buildkit which will be useful!

**Comment by totten** [comment]
@MikeyMJCO See #473
