### ISSUE TITLE
cividist and distmaker fail on Joomla Alt packages on MacOS 10.14.x

### ISSUE THREAD

**Issue by kcristiano** [civicrm/civicrm-buildkit#452]
When building Joomla tarballs on OSX the build will fail on the alternate Joomla install zip generation.

Specifically this occurs at https://github.com/civicrm/civicrm-core/blob/master/distmaker/dists/joomla_php5.sh#L40

```cp -r -p civicrm com_civicrm/admin/civicrm```  fails on the symlinked file ```vendor/pear/log/README.rst```

Changing the command to ```cp -aR civicrm com_civicrm/admin/civicrm```  allows both cividist and distmaker to complete successfully.

**Comment by MikeyMJCO** [comment]
@kcristiano is this resolved by the referenced PR? If yes can you close the issue?

**Comment by kcristiano** [comment]
Thanks for reminding me.  closing
