### ISSUE TITLE
add support for Ubuntu cosmic and disco

### ISSUE THREAD

**Issue by joemcl** [civicrm/civicrm-buildkit#453]
add Ubuntu cosmic and disco to https://github.com/civicrm/civicrm-buildkit/blob/master/bin/civi-download-tools .

**Comment by joemcl** [comment]
I can do a basic PR to add Ubuntu version info, but not sure how to update what version of what, like php, should be listed.

**Comment by joemcl** [comment]
Perhaps with what's listed here - https://github.com/civicrm/civicrm-core/blob/master/package.json

**Comment by seamuslee001** [comment]
![disco](https://media.giphy.com/media/DlGaTfcMeDmz6/giphy.gif)

@joemcl this is what sprang to mind seeing the PR title

**Comment by joemcl** [comment]
The Cosmic Disco!

**Comment by seamuslee001** [comment]
Closing this as PR has been merged
