### ISSUE TITLE
update debian builds to support buster, drop jessie

### ISSUE THREAD

**Issue by jmcclelland** [civicrm/civicrm-buildkit#462]
Now that buster is stable, we should support buster and drop support for jessie (if there is a reason to support jessie, let me know and I can update my patch).

**Comment by MikeyMJCO** [comment]
Commented on PR but Jessie is a valid and supported Debian LTS until 2020 and should remain supported until it goes EoL. https://wiki.debian.org/LTS

This matches what was discussed here #432

**Comment by MikeyMJCO** [comment]
Fixed and merged @jmcclelland can you close this issue?

**Comment by jmcclelland** [comment]
Thanks for the quick review and merge!
