### ISSUE TITLE
d8prj-clean builds install the demo database.

### ISSUE THREAD

**Issue by MikeyMJCO** [civicrm/civicrm-buildkit#515]
It seems that `d8prj-clean` builds (which should? be clean drupal8+civi) have the CiviCRM demo content in them?

See http://d8prj-clean.bkonaz.mjco.uk (login demo/demo)

**Comment by seamuslee001** [comment]
@MikeyMJCO just noting the main difference between a demo build and the clean build is 1) demo adds in the default dashboard dashlets 2) enables a bunch of additional extensions like CiviVolunteer and 3) enables CiviCase specifically but maybe other components by default which the clean version doesn't.
