### ISSUE TITLE
Work out how to enable patching for BuildKit template builds.

### ISSUE THREAD

**Issue by MikeyMJCO** [civicrm/civicrm-buildkit#561]
We will need to adapt the D8/D9 builds to account for the requirement to enable composer patching as per [this blog post](https://civicrm.org/blog/daved/action-required-drupal-8-installs-and-upgrades-composer-and-patches).

Options would include:

1. Build our own `CiviCRM + Drupal` composer `create-project` template (this also helps offer a simple install template for maintainers!). Obvious maintenance burden but relatively minor in the grand-scheme of things.

2. Patch the composer.json file offered by `drupal/recommended-project`. Potential for issues as that file changes - would seem to be a similar maintenance burden to 1 without the reuse potential.

3. Do nothing - accept that Buildkit builds won't match with what we're asking for normal installs (not sure this *is* an option really)

**Comment by MikeyMJCO** [comment]
@seamuslee001 @totten

**Comment by seamuslee001** [comment]
as long as they call civicrm_download_composer_d8 then it will work https://github.com/civicrm/civicrm-buildkit/blob/master/src/civibuild.lib.sh#L570

**Comment by MikeyMJCO** [comment]
Oh nice, so covered for Buildkit - thanks for pointing that out.

I'll open an issue against the D8 project to see if there's an appetite for a `create-project` in the CiviCRM namespace. Closing this.
