### ISSUE TITLE
Check for key length limits for utf8mb4 ?

### ISSUE THREAD

**Issue by ufundo** [civicrm/civicrm-buildkit#583]
Hi,

I had issues getting up and running with civibuild today on a fresh development environment due to hitting MYSQL key length limits for table creation on mariadb  Ver 15.1 Distrib 10.1.47-MariaDB.

First this was on creating the CiviCRM db itself (in particular the 'civicrm_extension' table).

This was solved by adding the following to my mysql server config (as per https://docs.civicrm.org/installation/en/latest/general/requirements/ ):

```
innodb_large_prefix=true
innodb_file_format=barracuda
innodb_file_per_table=true
```

But builds still crashed on table creation during install of bundled extensions ( searchkit in particular I think), until I added the additional, and less easy to find

`innodb_default_row_format = 'DYNAMIC'`

**Not sure which mysql/mariadb versions might hit this, but would it be appropriate for civi-download-tools to check this constraint and offer these mysql directives to remedy?**

--

full environment:
- Elementary OS 5.1
- mariadb  Ver 15.1 Distrib 10.1.47-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- apache Server version: Apache/2.4.29 (Ubuntu)
- php PHP 7.2.24-0ubuntu0.18.04.7 (cli) (built: Oct  7 2020 15:24:25) ( NTS )

**Comment by MikeyMJCO** [comment]
Elementary OS isn't one of the Distros we test against. If you're not using `--full` install methods we assume you've handled configuration yourself. Including the relevant options for MariaDB/MySQL.

**Comment by MikeyMJCO** [comment]
A note in the documentation might be worthwhile but I'm loathe to duplicate information that's already in the Installation/Requirements guide so perhaps a link!

**Comment by ufundo** [comment]
Hi ok, that seems fair enough, realise this may be an edge case!

The system requirements page is linked in the documentation already so not unreasonable to expect people to find it.

The `innodb_default_row_format` option isn't listed in the requirements documentation but I will take that up there...

Thanks!

**Comment by ufundo** [comment]
Sorry actually the Requirements page linked in that bit of the docs atm is this one: https://docs.civicrm.org/dev/en/latest/basics/requirements/ 

I think it would be useful to refer people to the Requirements in the installation guide which has details of server config stuff: https://docs.civicrm.org/installation/en/latest/general/requirements/

**Comment by seamuslee001** [comment]
I believe that docs change has been done closing
