### ISSUE TITLE
Clear out cached container when rebuilding

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/civicrm-buildkit#615]
I'm hitting an issue where my extension registers a log manager service. When I do a civibuild create it appears that the cached container is being loaded and it is loading my log manager before my full extension is installed causing errors. Do we remove these files when rebuilding @totten 

(I think I can work around this by fixing the deprecation warning that was trying to log and doing some exception catching for now)

**Comment by seamuslee001** [comment]
I don't believe we do but I'm sure Tim may have some ideas on this
