### ISSUE TITLE
Error applying patch for drupal (database.inc)

### ISSUE THREAD

**Issue by rubofvil** [civicrm/civicrm-buildkit#643]
The patch(mysql8-drupal.patch) in drupal7 can't be applied -> https://github.com/civicrm/civicrm-buildkit/blob/master/app/drupal-patches/mysql8-drupal.patch

The structure of the file database.inc was changed in the core of drupal. You can see in the next line.
https://git.drupalcode.org/project/drupal/-/blob/7.x/includes/database/mysql/database.inc#L366

Drupal now have a conditional to add/remove the param  `,NO_AUTO_CREATE_USER`
I tried to execute removing this part of the code in the patch, and seems that works fine

I don't know why is removed the param `,NO_AUTO_CREATE_USER`, but removing this part of patch seems that this param isn't inlcuded with the new release of drupal  (tested with protocol_version = 10 in mysql)

Query after install with **new patch**
```
MySQL [drupalcleancms_5p1y3]> SELECT @@sql_mode;
+-------------------------------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+-------------------------------------------------------------------------------------------------------------------------------------------+
```

**New Patch**
```
diff --git a/includes/database/mysql/database.inc b/includes/database/mysql/database.inc
index b836111987..0b9987f3de 100644
--- a/includes/database/mysql/database.inc
+++ b/includes/database/mysql/database.inc
@@ -457,6 +457,14 @@ class DatabaseConnection_mysql extends DatabaseConnection {
     }
   }
 
+  public function query($query, array $args = array(), $options = array()) {
+    $query = preg_replace('/{([^}]+)}/', '`\1`', $query);
+    // This to make Drush work
+    $query = str_replace(' system.', ' `system`.', $query);
+    $query = str_replace('`system` system', '`system` `system`', $query);
+    return parent::query($query, $args, $options);
+  }
+
   public function queryRange($query, $from, $count, array $args = array(), array $options = array()) {
     return $this->query($query . ' LIMIT ' . (int) $from . ', ' . (int) $count, $args, $options);
   }
 ```

**Comment by seamuslee001** [comment]
@rubofvil are you using the latest version of buildkit the test was changed here https://github.com/civicrm/civicrm-buildkit/blob/master/src/civibuild.lib.sh#L1062 and the core infrastructure that uses buildkit to generate the demo sites hasn't had any issues of late

**Comment by rubofvil** [comment]
> @rubofvil are you using the latest version of buildkit the test was changed here https://github.com/civicrm/civicrm-buildkit/blob/master/src/civibuild.lib.sh#L1062 and the core infrastructure that uses buildkit to generate the demo sites hasn't had any issues of late

Thx @seamuslee001! you are right, i used a version before this fix https://github.com/civicrm/civicrm-buildkit/commit/469a36fccadc7ab586bcf208079b8863bf17073f.

Closing the issue
