### ISSUE TITLE
ensure composer runs php7.3 in debian bullseye

### ISSUE THREAD

**Issue by jmcclelland** [civicrm/civicrm-buildkit#663]
In `civi-download-tools`, when the script detects Debian bullseye, we install php7.3 packages (using the sury repository).

However, the default php version in bullseye is 7.4. So, when composer runs via the command line, it runs php 7.4, and it complains about a missing mbstring php package.

The simple fix is to add:

`sudo update-alternatives --set php /usr/bin/php7.3`

But... I think a better fix is to remove sury, remove the php version number from the packages (to bring in the debian defaults) and let debian install the php-7.4 versions.

I am happy to prepare a PR using either stragegy based on feedback. I think the second option is the cleanest but the first option is more backward compatible.

**Comment by MegaphoneJon** [comment]
+1 for removing sury, given last week's dev-digest saying we're about to start pushing people toward 7.4.

**Comment by seamuslee001** [comment]
resolved via #668
