### ISSUE TITLE
Bump bknix min to php 7.3

### ISSUE THREAD

**Issue by colemanw** [civicrm/civicrm-buildkit#741]
Very soon CiviCRM won't be able to run on `bknix min` due to https://lab.civicrm.org/dev/core/-/issues/3991

**Comment by totten** [comment]
I brushed off the `php73` package to try it out. There was a problem with running `composer.phar` and `phpunit8.phar` -- these PHARs have SHA-512 checksums, which is fine on `php72` and `php74` but failed on `php73`. The PHAR issue should be fixed with #746.
