### ISSUE TITLE
[regression] Only run `drush language add` if there are languages to add

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/civicrm-buildkit#751]
My colleague is hitting an error here because `$NEW_LOCALES` is empty - a simple check before running it would prevent :-)

https://github.com/civicrm/civicrm-buildkit/commit/010a393d22b27edc84698f922fac53cbb8ce3bae#diff-7224d122e78711d88854f3fcc1c90b57ac817a458b24a2722f98852cf330b98fR1283 

He checked out an older version of buildkit & it worked fine

**Comment by eileenmcnaughton** [comment]
@totten not sure why this only affects his install not mine but the drush command is newly added

**Comment by ejegg** [comment]
I can reproduce this on a new install when I completely blow away my existing (wmff-flavored) drupal / civi build.
