### ISSUE TITLE
Update transifex-cli (cannot update transifex)

### ISSUE THREAD

**Issue by mlutfy** [civicrm/civicrm-buildkit#763]
The transifex-cli is now a Go package, instead of Python. The old client is not supported anymore, the API calls fail, so translations cannot be updated.

I found this blogpost, but I could not figure out how to update nix:  
http://lethalman.blogspot.com/2015/02/developing-in-golang-with-nix-package.html

I poked around here:  
https://github.com/civicrm/civicrm-buildkit/tree/master/nix/pkgs/transifexClient

And as far as I understand, we need something like this:

```
{ goPackages, lib, fetchFromGitHub, six, requests }:
buildGoModule rec {
  pname = "transifex-cli";
  version = "1.6.5";

  src = fetchFromGitHub {
    owner = "transifex";
    repo = "transifex-cli";
    rev = "${version}";
    sha256 = "FIXME"; // ?
  };

  modSha256 = "FIXME"; // ?

  subPackages = [ "cmd" ]; // random copy-paste, no idea what this is for

  meta = with stdenv.lib; {
    description = "Transifex CLI";
    homepage = "https://github.com/transifex/transifex-cli";
    license = licenses.asl20;
  };
}
```

but I just get this:

```
$ nix-shell -A min 
error: undefined variable 'buildGoModule'
```

for which there are zero helpful google results.

In `pkgs/transifexClient/default.nix`, I also tried replacing the python ref with:

```
transifexClient = import ./transifexClient.nix { };
```

but without success, same error.

All this feels weird, because as far as I understand, nix wants to build from source, but with go, it's much easier to use the binaries.

**Comment by totten** [comment]
@mlutfy That does have the about the right shape. A couple general thoughts:

* There's also a doc at https://nixos.org/manual/nixpkgs/stable/#sec-language-go. They tend to be more recent but also a bit thin.
* When I get confused, I often grep https://github.com/NixOS/nixpkgs/ for examples of similar packages. (*Compared to the manual and the blogs, that repo tends to be more recent+working.*)
* There is one big thing that differentiates `civicrm-buildkit` from canonical nix. The opening declaration like `{foo, bar}:` is often replaced with an explicit `import`. Noted here: https://github.com/civicrm/civicrm-buildkit/pull/764/commits/8b2258a3d432923638ac745fd127d62134acac19
* I took the example from above and did several small iterations in https://github.com/civicrm/civicrm-buildkit/pull/764. You should be able to check that out and try the `nix-shell -A min` again.

**Comment by totten** [comment]
> All this feels weird, because as far as I understand, nix wants to build from source, but with go, it's much easier to use the binaries.

Yeah, to use the binaries, you need to determine the environment (kernel + cpu) and then resolve the matching download URL.

It is fair to step back and consider ways to download this tool. Options would be:

1. Download it via `nix` (which needs a custom `*.nix` file)
2. Download it via `civi-download-tools` and `wget` (which needs some bits to pick the proper binary)
3. Download it via `civi-download-tools` and `go` (which makes `go` a pre-req)
4. Download it via `composer install` (`extra.downloads`) (*which doesn't do native binaries very well, but there was a contributor thinking about that*)

**Comment by totten** [comment]
It's deployed on `test-2`.
