### ISSUE TITLE
Civibuild create fails with Redis due to cached extensions

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/civicrm-buildkit#765]
When I run civibuild create wmff to recreate the wmff site (ie it has been used already & the cache is warm) it loads the list of hook-able extensions from Redis and it is the list that was enabled prior to the create. This means it is calling hooks (alterMenu) on extensions that are not enabled & fatals cos they call things that are not in the include path

Probably a judicious flushAll is enough - I'm not sure where though

Moved from https://github.com/totten/civix/issues/287

**Comment by eileenmcnaughton** [comment]
Yeah still a problem

**Comment by eileenmcnaughton** [comment]
keep it open

**Comment by eileenmcnaughton** [comment]
still open

**Comment by seamuslee001** [comment]
@eileenmcnaughton so when you run civibuild create the redis connection is defined somewhere right?

**Comment by eileenmcnaughton** [comment]
@seamuslee001 yeah - civicrm.settings.php - I note that @totten suggested a new constant 
define('CIVICRM_DEPLOY_ID', 'SoMe_RaNdOM_1234')

https://lab.civicrm.org/dev/core/-/issues/4159

**Comment by eileenmcnaughton** [comment]
I think we finally fixed it!
